/* Formatted on 25/02/2019 19:43:34 (QP5 v5.256.13226.35538) */
  SELECT N.V_POLICY_NO,
         TRIM (REGEXP_REPLACE (B.V_COMPANY_NAME, '[^a-zA-Z0-9]', ' '))
            SCHEME_NAME,
         N.V_PLAN_CODE,
         D_COMMENCEMENT,
         D_POLICY_END_DATE,
         COUNT (N.V_POLICY_NO) ACTIVE_LIVES,
         A.V_PYMT_FREQ,
         SUM (
              (N.N_IND_BASIC_PREM * 12)
            / DECODE (N.V_PYMT_FREQ, '00', 12, TO_NUMBER (N.V_PYMT_FREQ)))
            ANNUAL_PREMIUM,
         --         SUM (N.N_IND_BASIC_PREM) ANNUAL_PREMIUM,
         E.V_COMPANY_NAME AGENT_BROKER_NAME
    FROM GNMT_POLICY A,
         GNMM_COMPANY_MASTER B,
         AMMT_POL_AG_COMM C,
         AMMM_AGENT_MASTER D,
         GNMM_COMPANY_MASTER E,
         GNMT_POLICY_DETAIL N
   WHERE     A.V_CNTR_STAT_CODE = 'NB010'
         AND A.V_COMPANY_CODE = B.V_COMPANY_CODE
         AND A.V_COMPANY_BRANCH = B.V_COMPANY_BRANCH
         AND A.V_POLICY_NO = C.V_POLICY_NO
         AND C.V_ROLE_CODE = 'SELLING'
         AND C.N_AGENT_NO = D.N_AGENT_NO
         AND D.V_COMPANY_CODE = E.V_COMPANY_CODE
         AND D.V_COMPANY_BRANCH = E.V_COMPANY_BRANCH
         AND A.V_POLICY_NO = N.V_POLICY_NO
         AND N.V_CNTR_STAT_CODE = 'NB010'
GROUP BY N.V_POLICY_NO,
         N.V_PLAN_CODE,
         B.V_COMPANY_NAME,
         E.V_COMPANY_NAME,
         D.V_AGENT_CODE,
         D_COMMENCEMENT,
         D_POLICY_END_DATE,
         A.V_PYMT_FREQ
UNION
  SELECT N.V_POLICY_NO,
         TRIM (REGEXP_REPLACE (B.V_COMPANY_NAME, '[^a-zA-Z0-9]', ' '))
            SCHEME_NAME,
         N.V_PLAN_CODE,
         D_COMMENCEMENT,
         D_POLICY_END_DATE,
         COUNT (N.V_POLICY_NO) ACTIVE_LIVES,
         A.V_PYMT_FREQ,
         SUM (
              (N.N_RIDER_PREMIUM * 12)
            / DECODE (A.V_PYMT_FREQ, '00', 12, TO_NUMBER (A.V_PYMT_FREQ)))
            ANNUAL_PREMIUM,
--         SUM (N.N_RIDER_PREMIUM) ANNUAL_PREMIUM,
         E.V_COMPANY_NAME AGENT_BROKER_NAME
    FROM GNMT_POLICY A,
         GNMM_COMPANY_MASTER B,
         AMMT_POL_AG_COMM C,
         AMMM_AGENT_MASTER D,
         GNMM_COMPANY_MASTER E,
         GNMT_POLICY_RIDERS N
   WHERE     A.V_CNTR_STAT_CODE = 'NB010'
         AND A.V_COMPANY_CODE = B.V_COMPANY_CODE
         AND A.V_COMPANY_BRANCH = B.V_COMPANY_BRANCH
         AND A.V_POLICY_NO = C.V_POLICY_NO
         AND C.V_ROLE_CODE = 'SELLING'
         AND C.N_AGENT_NO = D.N_AGENT_NO
         AND D.V_COMPANY_CODE = E.V_COMPANY_CODE
         AND D.V_COMPANY_BRANCH = E.V_COMPANY_BRANCH
         AND A.V_POLICY_NO = N.V_POLICY_NO
         AND N.V_RIDER_STAT_CODE = 'NB010'
GROUP BY N.V_POLICY_NO,
         N.V_PLAN_CODE,
         B.V_COMPANY_NAME,
         E.V_COMPANY_NAME,
         D.V_AGENT_CODE,
         D_COMMENCEMENT,
         D_POLICY_END_DATE,
         A.V_PYMT_FREQ