/* Formatted on 25/02/2019 19:31:40 (QP5 v5.256.13226.35538) */
  SELECT TRIM (B.V_COMPANY_NAME) V_COMPANY_NAME,
         A.V_POLICY_NO,
         G.V_ADD_ONE,
         G.V_ADD_TWO,
         G.V_ADD_THREE,
         G.V_TOWN,
         G.V_POSTCODE,
         E.V_COMPANY_NAME V_AGENT_NAME,
         D.V_AGENT_CODE,
         (F.N_CONTRIBUTION) PREMIUM_LAST_RENEWAL,
         (F.N_SUM_COVERED) SUM_ASSURED,
         A.D_COMMENCEMENT,
         A.D_POLICY_END_DATE,
         A.D_POLICY_END_DATE + 1 RENEWAL_DATE,
         A.V_LASTUPD_USER,
         (SELECT V_CONTACT_NUMBER
            FROM GNDT_COMPMOBILE_CONTACTS H
           WHERE     H.V_COMPANY_CODE = B.V_COMPANY_CODE
                 AND H.V_COMPANY_BRANCH = B.V_COMPANY_BRANCH
                 AND V_CONTACT_NUMBER NOT LIKE '%@%'
                 AND ROWNUM = 1)
            TELEPHONE_NO,
         (SELECT V_CONTACT_NUMBER
            FROM GNDT_COMPMOBILE_CONTACTS H
           WHERE     H.V_COMPANY_CODE = B.V_COMPANY_CODE
                 AND H.V_COMPANY_BRANCH = B.V_COMPANY_BRANCH
                 AND V_CONTACT_NUMBER LIKE '%@%'
                 AND ROWNUM = 1)
            EMAIL,
         (SELECT DISTINCT BRH.V_BRANCH_NAME
            FROM GNMM_BRANCH_MASTER BRH
           WHERE BRH.V_BRANCH_CODE = A.V_POLICY_BRANCH AND ROWNUM = 1)
            POLICY_BRANCH,
         A.D_PROPOSAL_SUBMIT CREATION_DATE
    FROM GNMT_POLICY A,
         GNMM_COMPANY_MASTER B,
         AMMT_POL_AG_COMM C,
         AMMM_AGENT_MASTER D,
         GNMM_COMPANY_MASTER E,
         GNMT_QUOTATION F,
         GNDT_COMPANY_ADDRESS G
   WHERE     A.V_COMPANY_CODE = B.V_COMPANY_CODE
         AND A.V_COMPANY_BRANCH = B.V_COMPANY_BRANCH
         AND A.V_POLICY_NO = C.V_POLICY_NO
         AND C.V_ROLE_CODE = 'SELLING'
         AND C.N_AGENT_NO = D.N_AGENT_NO
         AND D.V_COMPANY_CODE = E.V_COMPANY_CODE
         AND B.V_COMPANY_CODE = G.V_COMPANY_CODE
         AND D.V_COMPANY_BRANCH = E.V_COMPANY_BRANCH
         AND A.V_QUOTATION_ID = F.V_QUOTATION_ID
         AND A.V_CNTR_STAT_CODE = 'NB010'
         AND C.V_STATUS = 'A'
         ORDER BY B.V_COMPANY_NAME