
select DISTINCT A.V_PLAN_CODE, 
(SELECT K.V_PLAN_NAME FROM gnmm_plan_master K WHERE K.V_PLAN_CODE = A.V_PLAN_CODE) PLAN_NAME,
A.V_EXCESS_PAYMENT_OPTION, 
DECODE (A.V_DEFAULT_OPTION, 'Y', 'Enabled', 'N', 'DISABLED') "Option",
B.V_PYMT_FREQ, 
(SELECT P.V_PYMT_DESC FROM Gnlu_Frequency_Master P WHERE P.V_PYMT_FREQ=B.V_PYMT_FREQ) PAYMENT_FREQUENCY,  
B.N_TP_MODAL_PREM_TIMES, B.N_FP_MODAL_PREM_TIMES, B.N_FP_MAX_POLICY_ANNIVERSARY
from  Gnmm_Plan_Excess_Pay_Options A, Gnmm_Plan_Paymode_Link B
WHERE A.V_PLAN_CODE =B.V_PLAN_CODE;
/



