
SELECT AGENCY,
V_AGENT_CODE,
 V_NAME, 
 UNITMANAGER,
  AGENCYMANAGER,
   V_POLICY_NO, 
   PROPOSAL_DATE, 
   POLICYNAME, 
   ISSUEDATE, 
POLICYSTATUS, 
IDNO, 
D_BIRTH_DATE, 
MARITALSTATUS, 
SEX,
 EMAIL, 
 PHONE, 
 D_APPOINTMENT, 
 D_TERMINATION,
  CURRENT_REPORTING,
  LAST_REPORTING, 
  OCCUPATION,
STARTDATE, 
V_PLAN_NAME, 
DESIGNATION,
 TRANS_DATE, 
  N_SEQ_NO, 
  ASSURED_NAME,
   POLICY_YEAR,
    D_PREMIUM_DUE, 
V_OVERRIDE,
 SUB_AGENT_CODE, 
 SUM(PREMIUM_AMT) PREMIUM_AMT, 
 SUM(N_COMM_AMT) N_COMM_AMT, 
 SUM(N_WHT) N_WHT,
  SUM(N_NET_COMM) N_NET_COMM,
   N_SUM_COVERED,
    N_CONTRIBUTION, 
    API,Payment_Method,
D_RECEIPT_DATE, 
ANNUALPREMIUM
FROM
(
SELECT a.N_AGENT_NO, C.V_AGENT_CODE, d.V_NAME,
JHL_GEN_PKG.GET_AGENCY_HIERARCHY(C.N_AGENT_NO,'30') UNITMANAGER, 
JHL_GEN_PKG.GET_AGENCY_HIERARCHY(C.N_AGENT_NO,'20') AGENCYMANAGER, g.D_PROPOSAL_SUBMIT PROPOSAL_DATE, G.V_PAYER_NAME POLICYNAME, G.D_ISSUE ISSUEDATE,
DECODE(g.V_STATUS,'A','ACTIVE','INACTIVE')POLICYSTATUS,

 --AGENT ID NUMBER---
 (SELECT  MAX(V_IDEN_NO)
                FROM GNDT_CUSTOMER_IDENTIFICATION CID
                WHERE    V_IDEN_CODE = 'NIC'
                AND  V_LASTUPD_INFTIM = (SELECT  max(V_LASTUPD_INFTIM)
                                                          FROM GNDT_CUSTOMER_IDENTIFICATION CID
                                                         WHERE    V_IDEN_CODE = 'NIC'
                                                          AND CID.N_CUST_REF_NO = C.N_CUST_REF_NO)
                AND N_CUST_REF_NO = C.N_CUST_REF_NO)IDNO, 
d.D_BIRTH_DATE,DECODE(d.V_MARITAL_STATUS,'M', 'MARRIED', 'S', 'SINGLE') MARITALSTATUS, DECODE(d.V_SEX,'M', 'MALE', 'F', 'FEMALE') SEX,
--AGENT EMAIL--
 (SELECT V_CONTACT_NUMBER
             FROM GNDT_CUSTMOBILE_CONTACTS
            WHERE     N_CUST_REF_NO = c.N_CUST_REF_NO--               AND V_STATUS = 'A'
                  AND V_Contact_Number LIKE '%@%'
                  AND ROWNUM = 1) EMAIL,
--AGENT PHONE--
  (SELECT V_CONTACT_NUMBER
             FROM GNDT_CUSTMOBILE_CONTACTS
            WHERE     N_CUST_REF_NO = c.N_CUST_REF_NO --               AND V_STATUS = 'A'
                  AND V_Contact_Number NOT LIKE '%@%'
                  AND ROWNUM = 1) PHONE, c.D_APPOINTMENT,c.D_TERMINATION,
 ( SELECT CM.V_NAME
 FROM  GNMT_CUSTOMER_MASTER CM
 WHERE CM.N_CUST_REF_NO = c.N_CURRENTLY_REPORTING_TO) CURRENT_REPORTING,
 ( SELECT CM.V_NAME
 FROM  GNMT_CUSTOMER_MASTER CM
 WHERE CM.N_CUST_REF_NO = c.N_LAST_REPORTING_TO) LAST_REPORTING, g.D_COMMENCEMENT STARTDATE, 
 
 ( SELECT G.V_OCCUP_DESC
 FROM  GNLU_OCCUP_MASTER G,GNMT_POLICY PM, GNMT_CUSTOMER_MASTER CM
 WHERE PM.N_PAYER_REF_NO = CM.N_CUST_REF_NO
 AND G.V_OCCUP_CODE = CM.V_OCCUP_CODE
 AND PM.V_POLICY_NO = g.V_POLICY_NO) OCCUPATION, h.V_PLAN_NAME,

V_DESCRIPTION DESIGNATION, e.V_ADD_THREE AGENCY, a.V_PLAN_CODE, D_COMM_GEN TRANS_DATE, a.V_POLICY_NO, 
a.N_SEQ_NO, b.V_NAME ASSURED_NAME, N_COMM_YEAR POLICY_YEAR, D_PREMIUM_DUE, N_PREM_AMT PREMIUM_AMT, a.V_RECEIPT_NO, N_COMM_AMT, N_COMM_RATE, 
NVL(V_INCOME_TAX_RULE_REF,0)/100*N_COMM_AMT N_WHT, N_COMM_AMT-NVL(V_INCOME_TAX_RULE_REF,0)/100*N_COMM_AMT N_NET_COMM, g.N_SUM_COVERED,G.N_CONTRIBUTION,
V_OC_FLAG V_OVERRIDE, BPG_AGENCY.BFN_GET_AGENT_CODE(N_SUB_AGENT_NO) SUB_AGENT_CODE, API,ins.V_Desc Payment_Method,RCT.D_RECEIPT_DATE,

DECODE(G.V_PYMT_FREQ,12,G.N_CONTRIBUTION,06,G.N_CONTRIBUTION*2,03,G.N_CONTRIBUTION*4,01,G.N_CONTRIBUTION*12,NULL)ANNUALPREMIUM

FROM AMMT_POL_COMM_DETAIL a, GNMT_POLICY_DETAIL b, AMMM_AGENT_MASTER c, GNMT_CUSTOMER_MASTER d, GNDT_CUSTOMER_ADDRESS e, 
AMMM_RANK_MASTER f, GNMT_POLICY g, GNMM_PLAN_MASTER h, JHL_SALESFORCE_DIGITAL_DATA j, REMT_RECEIPT rct, REMM_INSTRUMENT ins,  REMT_RECEIPT_INSTRUMENTS rct_ins
WHERE V_COMM_STATUS IN ('P')
AND a.V_POLICY_NO = b.V_POLICY_NO
AND a.N_SEQ_NO = b.N_SEQ_NO
AND a.N_AGENT_NO = c.N_AGENT_NO
AND A.V_POLICY_NO = J.V_POLICY_NO
AND c.N_CUST_REF_NO = d.N_CUST_REF_NO
AND c.N_CUST_REF_NO = e.N_CUST_REF_NO
AND c.V_RANK_CODE = f.V_RANK_CODE
AND c.N_CHANNEL_NO = f.N_CHANNEL_NO
AND B.V_POLICY_NO = G.V_POLICY_NO
AND g.V_PLAN_CODE = h.V_PLAN_CODE
AND a.V_POLICY_NO = rct.V_POLICY_NO
AND rct.N_RECEIPT_SESSION = rct_ins.N_RECEIPT_SESSION
And Rct_ins.V_INS_CODE = ins.V_INS_CODE
AND rct.V_RECEIPT_TABLE = 'DETAIL'
 AND rct.V_INSTRUMENT_STATUS = 'A'
 And Upper (Nvl (rct. V_Receipt_Remarks, 'XXXXX')) Not Like '%OFFLINE%'
-- And trunc(rct.D_Receipt_Date) BETWEEN :P_FM_DT AND :P_TO_DT 
--AND D_COMM_PAID BETWEEN :P_FM_DT AND :P_TO_DT 
--AND D_COMM_GEN BETWEEN '02-JAN-2018' AND '03-FEB-2018'
--AND C.V_AGENT_CODE = '6609'
--AND a.V_POLICY_NO = 'IL201500663512'
AND a.V_POLICY_NO NOT LIKE 'GL%'
--AND e.N_ADD_SEQ_NO=1
AND EXTRACT(YEAR FROM c.D_APPOINTMENT)>= 2023
)
GROUP BY V_AGENT_CODE, V_NAME, UNITMANAGER, AGENCYMANAGER, PROPOSAL_DATE, POLICYNAME, ISSUEDATE, POLICYSTATUS, IDNO, D_BIRTH_DATE, MARITALSTATUS, SEX, EMAIL,
 PHONE, D_APPOINTMENT, D_TERMINATION, CURRENT_REPORTING,LAST_REPORTING, OCCUPATION, STARTDATE,DESIGNATION, V_PLAN_NAME, AGENCY, TRANS_DATE, V_POLICY_NO, N_SEQ_NO, ASSURED_NAME, POLICY_YEAR, D_PREMIUM_DUE, 
V_OVERRIDE, SUB_AGENT_CODE, N_SUM_COVERED,N_CONTRIBUTION, API,PAYMENT_METHOD,D_RECEIPT_DATE,ANNUALPREMIUM
