/* Formatted on 26/01/2019 21:45:41 (QP5 v5.256.13226.35538) */
SELECT ( V_CLAIM_NO)  FROM 
(
SELECT A.V_CLAIM_NO,
       D.V_POLICY_NO,
       G.V_NAME,
       G.D_CNTR_START_DATE,
       G.D_CNTR_END_DATE,
       G.N_CONTRIBUTION,
       G.N_TERM,
       G.V_PLAN_CODE,
       D.N_SEQ_NO,
       N_CLIENT_REF_NO,
       D_IND_DOB,
       N_IND_SA,
       D.V_CLAIM_TYPE,
       V_DESCRIPTION CLAIM_TYPE,
       V_CLAIM_STATUS,
       V_STATUS_DESC,
       V_EVENT_CODE,
       NVL (N_AMOUNT_PAYABLE, 0) CLAIM_PROV,
       NVL (N_PROV_AMOUNT, 0) BONUS_PROV,
       NVL (GROSS_PAID, 0) GROSS_PAID,
         NVL (N_AMOUNT_PAYABLE, 0)
       + NVL (N_PROV_AMOUNT, 0)
       - NVL (GROSS_PAID, 0)
          CLAIM_OS,
       D_EVENT_DATE,
       D_CLAIM_DATE,
       A.V_LASTUPD_USER,
       V_CLIENT_NAME,
       DECODE (N_VOU_AMOUNT, NULL, NULL, A.D_LASTUPD_INFTIM) D_VOU_DATE,
       N_VOU_AMOUNT,
       JHL_UTILS.AGENT_NAME3 (D.V_POLICY_NO) AGENCY_NAME,
       P.V_POLICY_BRANCH
  FROM CLMT_CLAIM_MASTER A,
       CLLU_TYPE_MASTER B,
       CLMM_STATUS_MASTER C,
       CLDT_CLAIM_EVENT_POLICY_LINK D,
       CLDT_PROVISION_MASTER E,
       CLDT_BONUS_PROVISION F,
       GNMT_POLICY_DETAIL G,
       GNMT_POLICY P,
       (SELECT DISTINCT V_CLAIM_NO, D_EVENT_DATE FROM CLDT_CLAIM_EVENT_LINK)
       H,
       (  SELECT V_SOURCE_REF_NO,
                 NULL V_VOU_NO,
                 NULL V_MAIN_VOU_NO,
                 V_VOU_SOURCE,
                 NULL D_VOU_DATE,
                 SUM (N_VOU_AMOUNT) N_VOU_AMOUNT,
                 NULL V_CHQ_NO,
                 NULL V_PAYEE_NAME
            FROM PYMT_VOUCHER_ROOT A, PYMT_VOU_MASTER B
           WHERE A.V_MAIN_VOU_NO = B.V_MAIN_VOU_NO AND V_VOU_SOURCE = 'CLAIMS'
        GROUP BY V_SOURCE_REF_NO, V_VOU_SOURCE) I,
       (  SELECT V_CLAIM_NO, SUM (N_CLAIMANT_AMOUNT) GROSS_PAID
            FROM CLDT_CLAIMANT_MASTER
        GROUP BY V_CLAIM_NO) J
 WHERE     D.V_CLAIM_TYPE = B.V_CLAIM_TYPE(+)
       AND A.V_CLAIM_STATUS = C.V_STATUS_CODE
       AND A.V_CLAIM_NO = D.V_CLAIM_NO
       AND D.V_CLAIM_NO = E.V_CLAIM_NO(+)
       AND D.N_SUB_CLAIM_NO = E.N_SUB_CLAIM_NO(+)
       AND D.V_CLAIM_NO = F.V_CLAIM_NO(+)
       AND D.N_SUB_CLAIM_NO = F.N_SUB_CLAIM_NO(+)
       AND D.V_POLICY_NO = G.V_POLICY_NO
       AND D.V_POLICY_NO = P.V_POLICY_NO
       AND D.N_SEQ_NO = G.N_SEQ_NO
       AND A.V_CLAIM_NO = H.V_CLAIM_NO
       AND A.V_CLAIM_NO = I.V_SOURCE_REF_NO(+)
       AND A.V_CLAIM_NO = J.V_CLAIM_NO(+)
       
       ) where trunc(D_CLAIM_DATE) between '01-JAN-2024' AND '29-FEB-2024'