select * from gnmt_policy_detail where v_policy_no in ('UG202000585592','UG20170025323')
SELECT * FROM 
select * FROM  GNMM_POLICY_STATUS_MASTER

SELECT 
V_POLICY_NO,
V_NAME,
N_SALARY,
N_CONTRIBUTION,
N_EMPLOYER_CONTRIBUTION,
N_IND_SA,
N_IND_BASIC_PREM,
D_PREM_DUE_DATE,
D_NEXT_DUE_DATE,
V_CNTR_STAT_CODE,
(SELECT A.V_STATUS_DESC FROM GNMM_POLICY_STATUS_MASTER A  WHERE  A.V_STATUS_CODE=V_CNTR_STAT_CODE) STATUS,
D_IND_DOB,
N_INDSA_REQUEST,
N_INDPREM_REQUEST,
N_IND_NET_CONTRIBUTION,
N_IND_NET_BASIC_PREM,
D_CNTR_END_DATE,
D_ENTRY_DATE
from gnmt_policy_detail where v_policy_no in ('UG202000585592','UG201700257323')
ORDER BY 1 ASC