SELECT
    *
FROM
    ALL_DEPENDENCIES
WHERE
    REFERENCED_TYPE = 'TYPE'
    AND REFERENCED_NAME = 'CL_GCL_FRM_45_CNTR_TYPE';
    
    SELECT
    *
FROM
    USER_DEPENDENCIES
WHERE
    REFERENCED_TYPE = 'TYPE'
    AND REFERENCED_NAME = 'CL_GCL_FRM_45_CNTR_TYPE';
    
    SELECT
    *
FROM
    DBA_DEPENDENCIES
WHERE
    REFERENCED_TYPE = 'TYPE'
    AND REFERENCED_NAME = 'CL_GCL_FRM_45_CNTR_TYPE';