Select * from  GNMT_POLICY
/
SELECT 
 POLICY.V_POLICY_NO,
  POLICY.N_CONTRIBUTION,
  'UGX' AS CURRENCY,
  DECODE (POLICY.V_PYMT_FREQ, '01', 'MONTHLY', '03', 'QUARTELY', '06', 'HALF YEARLY', '12', 'Yearly') INTERVAL,
   (
    SELECT 
      V_CONTACT_NUMBER 
    FROM 
      GNDT_CUSTMOBILE_CONTACTS 
    WHERE 
      N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO 
      AND V_CONTACT_CODE = 'CONT010' OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) MOBILE_PHONE_NUMBER, 
  (
    SELECT 
      V_PLAN_NAME 
    FROM 
      GNMM_PLAN_MASTER 
    WHERE 
      V_PLAN_CODE = POLICY.V_PLAN_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) PRODUCT, 
    (
    SELECT 
      V_IDEN_NO 
    FROM 
      GNDT_CUSTOMER_IDENTIFICATION 
    WHERE 
      N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO 
      AND V_IDEN_CODE IN ('PIN', 'NIC') 
      /*AND V_IDEN_CODE IS NOT NULL*/
    ORDER BY 
      V_IDEN_CODE DESC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) INDENTITY_NO, 
    (
    SELECT 
      V_NAME 
    FROM 
      GNMT_CUSTOMER_MASTER 
    WHERE 
      N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) HOLDER_NAME, 
    (
    SELECT 
      V_CONTACT_NUMBER 
    FROM 
      GNDT_CUSTMOBILE_CONTACTS 
    WHERE 
      N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO 
      AND V_CONTACT_CODE = 'CONT003' OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) EMAIL, 
   D_POLICY_END_DATE AS POLICY_END_DATE, 
     D_COMMENCEMENT  "EFFECTIVE_DATE/COMMENCEMENT_DATE", 
  POL_STATUS.V_STATUS_DESC AS STATUS, 
  D_ISSUE AS ORIG_POLICY_START_DATE,  
  N_PROPOSER_REF_NO, 
  (
    SELECT 
      V_ADD_ONE 
    FROM 
      GNDT_CUSTOMER_ADDRESS 
    WHERE 
      N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO 
      AND V_ADD_CODE = 'ADR001' OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) RESIDENCE_ADDRESS, 
  (
    SELECT 
      V_IDEN_CODE 
    FROM 
      GNDT_CUSTOMER_IDENTIFICATION 
    WHERE 
      N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO 
      AND V_IDEN_CODE IN ('PIN', 'NIC') 
      /*AND V_IDEN_CODE IS NOT NULL*/
    ORDER BY 
      V_IDEN_CODE DESC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) INDENTITY_TYPE, 
  --(SELECT V_OCCUP_DESC FROM GNLU_OCCUP_MASTER WHERE V_OCCUP_CODE = POLICY.V_OCCUP_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY )  OCCUPATION,
  (
    SELECT 
      V_OCCUP_DESC 
    FROM 
      GNLU_OCCUP_MASTER 
    WHERE 
      V_OCCUP_CODE = (
        SELECT 
          V_OCCUP_CODE 
        FROM 
          GNMT_CUSTOMER_MASTER 
        WHERE 
          N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
      )
  ) OCCUPATION, 
  (
    SELECT 
      V_CONTACT_NUMBER 
    FROM 
      GNDT_CUSTMOBILE_CONTACTS 
    WHERE 
      N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO 
      AND V_CONTACT_CODE = 'CONT007' OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) RESIDENCE_PHONE_NUMBER, 
  (
    SELECT 
      V_CONTACT_NUMBER 
    FROM 
      GNDT_CUSTMOBILE_CONTACTS 
    WHERE 
      N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO 
      AND V_CONTACT_CODE = 'CONT009' OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) OFFICE_PHONE_NUMBER, 
  V_UNDERWRITER 
FROM 
  GNMT_POLICY POLICY 
  LEFT JOIN GNMM_POLICY_STATUS_MASTER POL_STATUS ON POLICY.V_CNTR_STAT_CODE = POL_STATUS.V_STATUS_CODE 
--WHERE 
--  V_POLICY_NO NOT LIKE '%UG%' 
--  AND TRUNC(D_ISSUE) BETWEEN TO_DATE('01/01/2023', 'DD/MM/RRRR') 
--  AND TO_DATE('28/02/2023', 'DD/MM/RRRR') --AND POL_STATUS.V_STATUS_DESC IN ('IN-FORCE')
--  AND POLICY.V_POLICY_NO IN (
--    'UI202300901504', 'UI202300907126', 
--    'UI202300905273'
--  ) --ORDER BY D_ISSUE DESC
--  
  
ORDER BY 
  D_ISSUE DESC;
  /


select distinct V_CONTACT_CODE from GNDT_CUSTMOBILE_CONTACTS  N_CUST_REF_NO, V_CONTACT_CODE, V_CONTACT_NUMBER
CONT010
CONT007
CONT003

select * from GNMT_POLICY V_POLICY_NO, PROPOSER_REF_NO 

select distinct V_CONTACT_CODE  from GNDT_CUSTMOBILE_CONTACTS  where V_CONTACT_NUMBER is not null 
CONT003
CONT001
CONT004
CONT009
CONT008
CONT011
CONT010
CONT007
CONT002
CONT006
CONT005
CONT012
/
SELECT 
    p.V_POLICY_NO,
    MAX(CASE WHEN c.V_CONTACT_CODE = 'CONT003' THEN c.V_CONTACT_NUMBER END) AS CONT003,
    MAX(CASE WHEN c.V_CONTACT_CODE = 'CONT001' THEN c.V_CONTACT_NUMBER END) AS CONT001,
    MAX(CASE WHEN c.V_CONTACT_CODE = 'CONT004' THEN c.V_CONTACT_NUMBER END) AS CONT004,
    MAX(CASE WHEN c.V_CONTACT_CODE = 'CONT009' THEN c.V_CONTACT_NUMBER END) AS CONT009,
    MAX(CASE WHEN c.V_CONTACT_CODE = 'CONT008' THEN c.V_CONTACT_NUMBER END) AS CONT008,
    MAX(CASE WHEN c.V_CONTACT_CODE = 'CONT011' THEN c.V_CONTACT_NUMBER END) AS CONT011,
    MAX(CASE WHEN c.V_CONTACT_CODE = 'CONT010' THEN c.V_CONTACT_NUMBER END) AS CONT010,
    MAX(CASE WHEN c.V_CONTACT_CODE = 'CONT007' THEN c.V_CONTACT_NUMBER END) AS CONT007,
    MAX(CASE WHEN c.V_CONTACT_CODE = 'CONT002' THEN c.V_CONTACT_NUMBER END) AS CONT002,
    MAX(CASE WHEN c.V_CONTACT_CODE = 'CONT006' THEN c.V_CONTACT_NUMBER END) AS CONT006,
    MAX(CASE WHEN c.V_CONTACT_CODE = 'CONT005' THEN c.V_CONTACT_NUMBER END) AS CONT005,
    MAX(CASE WHEN c.V_CONTACT_CODE = 'CONT012' THEN c.V_CONTACT_NUMBER END) AS CONT012
FROM 
    GNMT_POLICY p
LEFT JOIN 
    GNDT_CUSTMOBILE_CONTACTS c
ON 
    p.N_PROPOSER_REF_NO  = c.N_CUST_REF_NO
    where  p.V_POLICY_NO not like '%UG%'
GROUP BY 
    p.V_POLICY_NO
ORDER BY 
    p.V_POLICY_NO desc;
/