select A.V_NAME, A.* from gnmt_policy_detail A where A.v_policy_no = 'UG202100793355' 
AND to_char(A.V_LASTUPD_INFTIM, 'MON-YY') = 'APR-24'

select * from gnmt_policy where v_policy_no = 'UG201900513146'
--01/10/2023  D_COMMENCEMENT
select * from gnmt_policy_detail where v_policy_no = 'UG201900513146'


D_CNTR_START_DATE
D_CNTR_END_DATE

select 
V_NAME,
V_GROUP_CODE,
N_SALARY,
N_IND_SA,
V_CNTR_STAT_CODE,
D_CNTR_START_DATE,
D_CNTR_END_DATE,
V_CNTR_PREM_STAT_CODE,
(SELECT V_STATUS_DESC FROM GNMM_POLICY_STATUS_MASTER WHERE V_STATUS_CODE =V_CNTR_PREM_STAT_CODE) CUST_STAT
FROM GNMT_POLICY_DETAIL
WHERE V_POLICY_NO LIKE 'UG%' 
ORDER BY 6 DESC

    CUST_STATUS


SELECT * FROM GNMM_POLICY_STATUS_MASTER