/*
Author Frank Bagambe
Description  KYC for Corporate
*/

-- SELECT * FROM GNMT_POLICY   --V_COMPANY_CODE, V_CNTR_STAT_CODE
--SELECT * FROM GNMM_POLICY_STATUS_MASTER V_CNTR_STAT_CODE = V_STATUS_DESC
SELECT 
COMPANY_CODE,    
V_COMPANY_BRANCH,    
V_CNTR_STAT_CODE,    
V_COMPANY_NAME,
(SELECT V_STATUS_DESC FROM GNMM_POLICY_STATUS_MASTER WHERE V_STATUS_CODE=V_CNTR_STAT_CODE) AS STATUS,      
TIN,    
REG_NO,    
V_CONTACT_NUMBER,    
V_CONTACT_PERSON,    
V_CONTACT_PERSON_DESIG,    
V_CONTACT_NUMBER_2,    
V_ADD_ONE,    
V_ADD_TWO,    
V_ADD_THREE,    
V_STATE_CODE,    
V_COUNTRY_CODE,    
V_POST_BOX,    
BENEFICIARY_OWNER_ID,    
BENEFICIARY_OWNER_NAME
FROM 
(
SELECT 
COMPANY_CODE,
V_COMPANY_BRANCH, 
--(SELECT V_COMPANY_CODE FROM GNMT_POLICY WHERE V_COMPANY_CODE= COMPANY_CODE), --OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
--(SELECT V_CNTR_STAT_CODE FROM GNMT_POLICY WHERE V_COMPANY_CODE= COMPANY_CODE AND ROWNUM =1),
(SELECT V_CNTR_STAT_CODE FROM GNMT_POLICY WHERE V_COMPANY_CODE= COMPANY_CODE AND V_COMPANY_CODE IS NOT NULL OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY) AS V_CNTR_STAT_CODE,
V_COMPANY_NAME,    
TIN,    
REG_NO,    
V_CONTACT_NUMBER,    
V_CONTACT_PERSON,    
V_CONTACT_PERSON_DESIG,    
V_CONTACT_NUMBER_2,    
V_ADD_ONE,    
V_ADD_TWO,    
V_ADD_THREE,    
V_STATE_CODE,    
V_COUNTRY_CODE,    
V_POST_BOX,    
BENEFICIARY_OWNER_ID,    
BENEFICIARY_OWNER_NAME
FROM 
(
select 
  A.V_COMPANY_CODE AS COMPANY_CODE, 
  A.V_COMPANY_BRANCH, 
  A.V_COMPANY_NAME, 
  A.V_REGN_NO AS "TIN", 
  A.V_COMP_GROUP_CODE AS "REG_NO", 
  (
    SELECT 
      V_CONTACT_NUMBER 
    FROM 
      GNDT_COMPMOBILE_CONTACTS B 
    WHERE 
      A.V_COMPANY_CODE = B.V_COMPANY_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) V_CONTACT_NUMBER, 
  (
    SELECT 
      V_CONTACT_PERSON 
    FROM 
      GNDT_COMPMOBILE_CONTACTS B 
    WHERE 
      A.V_COMPANY_CODE = B.V_COMPANY_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) V_CONTACT_PERSON, 
  (
    SELECT 
      V_CONTACT_PERSON_DESIG 
    FROM 
      GNDT_COMPMOBILE_CONTACTS B 
    WHERE 
      A.V_COMPANY_CODE = B.V_COMPANY_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) V_CONTACT_PERSON_DESIG, 
  (
    SELECT 
      V_CONTACT_NUMBER 
    FROM 
      GNDT_COMPADD_CONTACTS C 
    WHERE 
      A.V_COMPANY_CODE = C.V_COMPANY_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) V_CONTACT_NUMBER_2, 
  --B.V_CONTACT_NUMBER,B.V_CONTACT_PERSON,B.V_CONTACT_PERSON_DESIG, C.V_CONTACT_NUMBER,
  (
    SELECT 
      V_ADD_ONE 
    FROM 
      GNDT_COMPANY_ADDRESS D 
    WHERE 
      A.V_COMPANY_CODE = D.V_COMPANY_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) V_ADD_ONE, 
  (
    SELECT 
      V_ADD_TWO 
    FROM 
      GNDT_COMPANY_ADDRESS D 
    WHERE 
      A.V_COMPANY_CODE = D.V_COMPANY_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) V_ADD_TWO, 
  (
    SELECT 
      V_ADD_THREE 
    FROM 
      GNDT_COMPANY_ADDRESS D 
    WHERE 
      A.V_COMPANY_CODE = D.V_COMPANY_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) V_ADD_THREE, 
  (
    SELECT 
      V_STATE_CODE 
    FROM 
      GNDT_COMPANY_ADDRESS D 
    WHERE 
      A.V_COMPANY_CODE = D.V_COMPANY_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) V_STATE_CODE, 
  (
    SELECT 
      V_COUNTRY_CODE 
    FROM 
      GNDT_COMPANY_ADDRESS D 
    WHERE 
      A.V_COMPANY_CODE = D.V_COMPANY_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) V_COUNTRY_CODE, 
  (
    SELECT 
      V_POST_BOX 
    FROM 
      GNDT_COMPANY_ADDRESS D 
    WHERE 
      A.V_COMPANY_CODE = D.V_COMPANY_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) V_POST_BOX, 
  -- D.V_ADD_ONE,D.V_ADD_TWO, D.V_ADD_THREE, D.V_STATE_CODE,D.V_COUNTRY_CODE,D.V_POST_BOX,
  (
    SELECT 
      V_IDEN_NO 
    FROM 
      GNMT_BENEFICIAL_OWNER E 
    WHERE 
      A.V_COMPANY_CODE = E.V_COMPANY_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
  ) BENEFICIARY_OWNER_ID, 
  (
    select 
      V_NAME 
    from 
      gnmt_customer_master 
    where 
      N_CUST_REF_NO in (
        select 
          N_CUST_REF_NO 
        from 
          GNDT_CUSTOMER_IDENTIFICATION 
        where 
          V_IDEN_NO =(
            SELECT 
              V_IDEN_NO 
            FROM 
              GNMT_BENEFICIAL_OWNER E 
            WHERE 
              A.V_COMPANY_CODE = E.V_COMPANY_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY
          )
      )
  ) BENEFICIARY_OWNER_NAME -- E.V_IDEN_NO AS BENEFICIARY_OWNER_ID,
  -- E.V_IDEN_NO AS BENEFICIARY_OWNER_NAME
  --SELECT V_CNTR_STAT_CODE FROM GNMT_POLICY WHERE V_COMPANY_CODE =
from 
  GNMM_COMPANY_MASTER A --LEFT JOIN GNDT_COMPMOBILE_CONTACTS B ON A.V_COMPANY_CODE = B.V_COMPANY_CODE
  --LEFT JOIN GNDT_COMPADD_CONTACTS C ON A.V_COMPANY_CODE = C.V_COMPANY_CODE
  --LEFT JOIN GNDT_COMPANY_ADDRESS D ON A.V_COMPANY_CODE = D.V_COMPANY_CODE
  --LEFT JOIN GNMT_BENEFICIAL_OWNER E ON A.V_COMPANY_CODE = E.V_COMPANY_CODE
WHERE 
  A.V_COMPANY_CODE IN (
    SELECT 
      V_COMPANY_CODE 
    FROM 
      GNMT_POLICY 
    where 
      V_CNTR_STAT_CODE = 'NB010' 
      and V_POLICY_NO like ('UG%') 
      AND TO_DATE(V_LASTUPD_INFTIM, 'DD/MM/RRRR') BETWEEN TO_DATE('01-JAN-21', 'DD/MM/RRRR') 
      AND TO_DATE('30-NOV-2023', 'DD/MM/RRRR') 
    GROUP BY 
      V_COMPANY_CODE
  )

)
)