
WITH OutstandingPremium AS (
    SELECT 
        D_PREM_DUE_DATE,
        N_CONTRIBUTION,
        V_POLICY_NO,
        ROUND(MONTHS_BETWEEN(SYSDATE, D_PREM_DUE_DATE)) AS OUTSTANDING_MONTHS
    FROM 
        GNMT_POLICY
    WHERE 
        V_POLICY_NO IN ('UI202200756074','UI202200781985','UI202200780401') -- Extend this to multiple policy numbers as needed
),
GeneratedMonths AS (
    SELECT LEVEL AS MONTH_NUM
    FROM DUAL 
    CONNECT BY LEVEL <= (SELECT MAX(OUTSTANDING_MONTHS) FROM OutstandingPremium)
),
MonthlyInterestCalculation AS (
    SELECT
        op.V_POLICY_NO,
        op.D_PREM_DUE_DATE,
        op.N_CONTRIBUTION,
        op.OUTSTANDING_MONTHS,
        gm.MONTH_NUM,
        (gm.MONTH_NUM * op.N_CONTRIBUTION) AS CUMULATIVE_OUTSTANDING_PREMIUM,
        (gm.MONTH_NUM * op.N_CONTRIBUTION) * (1.3 / 100) AS INTEREST_AMOUNT,
        SUM((gm.MONTH_NUM * op.N_CONTRIBUTION) * (1.3 / 100)) OVER (PARTITION BY op.V_POLICY_NO ORDER BY gm.MONTH_NUM) AS CUMULATIVE_INTEREST
    FROM 
        OutstandingPremium op
    CROSS JOIN GeneratedMonths gm
    WHERE 
        gm.MONTH_NUM <= op.OUTSTANDING_MONTHS
)
SELECT 
    V_POLICY_NO,
    (SYSDATE - D_PREM_DUE_DATE) AS OUTSTANDING_DAYS, 
    N_CONTRIBUTION,  
    OUTSTANDING_MONTHS * N_CONTRIBUTION AS TOTAL_OUTSTANDING_PREMIUM,
    MAX(CUMULATIVE_INTEREST) AS PREMIUM_OUTSTANDING_INTEREST_AMOUNT
FROM 
    MonthlyInterestCalculation
GROUP BY 
    V_POLICY_NO, D_PREM_DUE_DATE, N_CONTRIBUTION, OUTSTANDING_MONTHS;
/
