
select count (distinct SCHEMECODE) from
--(
SELECT  DAUG.GET_SCHEME_TYPE2(C.SCHEMECODE,C.COMPANYCODE) LOB,S.SCHEMECODE, 
S.SCHEMENAME,C.COMPANYNAME, S.RBAREGNO,S.KRA_PIN,S.PHONE,S.EMAIL, S.STREET,
 S.RBAREGDATE, C.PV_PIN 
FROM  DAUG.GPNC_SCHEME S,  DAUG.GPNC_SCHEMECOMPANY C
WHERE S.SCHEMECODE = C.SCHEMECODE 
AND S.SCHEMECODE NOT IN ('100999','1009993') 
--and  (C##ONSULTIT.GET_SCHEME_TYPE2(C.SCHEMECODE,C.COMPANYCODE) = :P_LOB OR  :P_LOB IS NULL)
AND C.PV_STATUS = 'A'
--)