/* Formatted on 23/01/2020 15:43:40 (QP5 v5.256.13226.35538) */
SELECT a.V_POLICY_NO,
       V_TYPE,
       N_CONTRIBUTION,
       N_AMOUNT,
       V_CNTR_STAT_CODE,
       V_STATUS_DESC,
       b.V_LASTUPD_USER,
       D_PREM_DUE_DATE,
       D_NEXT_OUT_DATE,
       D_COMMENCEMENT,
       D_POLICY_END_DATE,
       JHL_UTILS.AGENT_NAME (d.N_AGENT_NO) AGENT
  FROM PPMT_OVERSHORT_PAYMENT a,
       GNMT_POLICY b,
       GNMM_POLICY_STATUS_MASTER c,
       AMMT_POL_AG_COMM d
 WHERE     a.V_POLICY_NO = b.V_POLICY_NO
       AND V_STATUS_CODE = V_CNTR_STAT_CODE
       AND b.V_POLICY_NO = d.V_POLICY_NO
       AND V_ROLE_CODE = 'SELLING'
       AND d.V_STATUS = 'A'
       AND N_AMOUNT > 0
       AND a.V_POLICY_NO NOT LIKE 'GL%'
--AND a.V_POLICY_NO ='209198'
UNION ALL
  SELECT a.V_POLICY_NO,
         'O' V_TYPE,
         N_CONTRIBUTION,
         SUM (N_AMOUNT) N_AMOUNT,
         V_CNTR_STAT_CODE,
         V_STATUS_DESC,
         b.V_LASTUPD_USER,
         D_PREM_DUE_DATE,
         D_NEXT_OUT_DATE,
         D_COMMENCEMENT,
         D_POLICY_END_DATE,
         JHL_UTILS.AGENT_NAME (d.N_AGENT_NO) AGENT
    FROM PPDT_PROPOSAL_DEPOSIT a,
         GNMT_POLICY b,
         GNMM_POLICY_STATUS_MASTER c,
         AMMT_POL_AG_COMM d
   WHERE     a.V_POLICY_NO = b.V_POLICY_NO
         AND V_STATUS_CODE = V_CNTR_STAT_CODE
         AND b.V_POLICY_NO = d.V_POLICY_NO
         AND V_ROLE_CODE = 'SELLING'
         AND d.V_STATUS = 'A'
         AND a.V_POLICY_NO NOT LIKE 'GL%'
         AND a.V_STATUS = 'A'
GROUP BY a.V_POLICY_NO,
         N_CONTRIBUTION,
         V_CNTR_STAT_CODE,
         V_STATUS_DESC,
         b.V_LASTUPD_USER,
         D_PREM_DUE_DATE,
         D_NEXT_OUT_DATE,
         D_COMMENCEMENT,
         D_POLICY_END_DATE,
         JHL_UTILS.AGENT_NAME (d.N_AGENT_NO)