select * from GNDT_GL_DETAILS  where N_REF_NO =2023008380
29272510
33764557

29272499
33764517
/

SELECT *
FROM JHL_ISF_OFA_ACC_MAP
WHERE ISF_GL_CODE IN (SELECT V_GL_CODE 
                     FROM GNDT_GL_DETAILS 
                     WHERE /*V_DOCU_REF_NO*/ N_REF_NO = 29272499/* '2023008380'*/ )
  AND ACC_DESC IN (SELECT DISTINCT V_DESC 
                  FROM GNDT_GL_DETAILS 
                  WHERE /*V_DOCU_REF_NO */ N_REF_NO = 29272499 /* '2023008380'*/);
                  /
                  
SELECT M.N_REF_NO, M.V_JOURNAL_STATUS, D.V_GL_CODE, D.V_DESC, D.N_AMT, D.V_TYPE
FROM GNMT_GL_MASTER M
JOIN GNDT_GL_DETAILS D ON M.N_REF_NO = D.N_REF_NO
WHERE M.V_DOCU_REF_NO = '2023008379';

/

SELECT *
FROM JHL_OFA_PYMT_TRANSACTIONS
WHERE V_VOU_NO = '2023008379';

/


SELECT *
FROM XXJICUG_AP_INVOICES_STG@JICOFPROD.COM
WHERE VOUCHER_NUM = '2023008380'
  AND OPERATING_UNIT = 'JHL_UG_LIF_OU';
/


-- supplier
SELECT *
FROM JHL_OFA_SUPPLIER
WHERE N_CUST_REF_NO = (SELECT N_CUST_REF_NO 
                       FROM JHL_OFA_PYMT_TRANSACTIONS 
                       WHERE V_VOU_NO = '2023008380');
                       /

-- For Corporate Supplier
SELECT *
FROM JHL_OFA_CO_SUPPLIER
WHERE V_COMPANY_CODE = (SELECT V_COMPANY_CODE 
                        FROM JHL_OFA_PYMT_TRANSACTIONS 
                        WHERE V_VOU_NO = '2023008380');
                        /


--payment and voucher details

SELECT *
FROM PYMT_VOU_MASTER PV
JOIN PYMT_VOUCHER_ROOT PM ON PM.V_MAIN_VOU_NO = PV.V_MAIN_VOU_NO
WHERE PV.V_VOU_NO = '2023008380';

/


-- Create supplier individual Supplier
BEGIN
   CREATE_INDIVIDUAL_SUPPLIER(V_CUST_REF_NO => 123456);
END;
/

-- Create supplier cooperate Supplier

BEGIN
   CREATE_CORPORATE_SUPPLIER(COMPANY_CODE = 'BLESSED EVENTS', COMPANY_BRANCH = 'KLA');
END;
/
/* BLESSED EVENTS  KLA */
---- Checking whether Supplier has Created

SELECT *
FROM JHL_OFA_SUPPLIER
WHERE N_CUST_REF_NO = 123456;
/
-- for corporate
SELECT *
FROM JHL_OFA_CO_SUPPLIER
WHERE V_COMPANY_CODE = 'COMP123'
  AND V_COMPANY_BRANCH = 'BR001';
  
-- Checking other Information
SELECT *
FROM JHL_OFA_SUPPLIER_SITE
WHERE N_CUST_REF_NO = <V_CUST_REF_NO>;

/


SELECT *
FROM  GNMM_COMPANY_MASTER
WHERE V_COMPANY_CODE = 'BLESSED EVENTS'
  AND V_COMPANY_BRANCH = 'KLA';
  /
--001DFCU
SELECT *
FROM  GNMM_COMPANY_MASTER
WHERE V_COMPANY_CODE = '001DFCU'
  AND V_COMPANY_BRANCH = 'HO';
  /
  
  SELECT *
FROM JHL_OFA_CO_SUPPLIER
WHERE V_COMPANY_CODE = 'BLESSED EVENTS'
  AND V_COMPANY_BRANCH = 'KLA';
  /
  
  SELECT *
FROM ALL_PROCEDURES
WHERE OBJECT_NAME = 'CREATE_CORPORATE_SUPPLIER';
/
SELECT *
FROM ALL_ARGUMENTS
WHERE OBJECT_NAME = 'CREATE_CORPORATE_SUPPLIER';
/

BEGIN
   JHLISFUADM.CREATE_CORPORATE_SUPPLIER(
       COMPANY_CODE   => 'BLESSED_EVENTS',  -- Replace with your company code
       COMPANY_BRANCH => 'KLA',             -- Replace with your company branch
       V_AGENT_NO     => NULL               -- If you have an agent number, replace NULL with the actual number
   );
END;
/


SELECT OBJECT_NAME, OBJECT_TYPE
FROM USER_PROCEDURES
WHERE OBJECT_NAME = 'CREATE_CORPORATE_SUPPLIER';
/


BEGIN
   JHL_OFA_UTILS_1.CREATE_CORPORATE_SUPPLIER
   (COMPANY_CODE => 'BLESSED_EVENTS', COMPANY_BRANCH => 'KLA', V_AGENT_NO     => NULL );
END;
/
--COMMIT

SELECT * FROM GNMT_GL_MASTER WHERE V_DOCU_REF_NO ='2023008379';
/
  SELECT * FROM PYMT_VOU_MASTER WHERE V_VOU_NO IN 
 ('2024001764');
/
    SELECT * FROM PYDT_VOU_DETAILS WHERE V_VOU_NO='2023008380'
    
        SELECT * FROM PYDT_VOUCHER_POLICY_CLIENT WHERE V_VOU_NO='2023000166'
        
        SELECT *
FROM     GNMM_COMPANY_MASTER
WHERE V_COMPANY_CODE = 'SIHL'
  AND V_COMPANY_BRANCH = 'KLA';