/*provision Sumary Commission*/
SELECT DISTINCT  BILL.V_POLICY_NO,
POL.V_PLAN_CODE,
V_PLAN_NAME, 
BILL_REQ_GRP.V_PLRI_CODE,  
 DECODE(BILL.V_BILL_TYPE, 'CN', 'CREDIT NOTE','DN', 'DEBIT NOTE' ) BILL_TYPE,
C.V_SHORT_NAME BILL_SOURCE, BILL.V_BILL_NO,
 N_BILL_AMT,
D_BILL_RAISED_DATE D_BILL_RAISED,  BILL.D_BILL_DUE_DATE,
 N_COMM_PCT,
 N_COMM_AMT

FROM GNDT_BILL_TRANS BILL, LU_CODES C, Gnmm_Company_Master CO,GNMT_POLICY POL,GNMM_PLAN_MASTER PROD,
(
select BILL_REQ.V_POLICY_NO, BILL_REQ.V_BILL_NO, BILL_REQ.V_PLRI_CODE,
sum(DECODE (BILL_REQ.V_BILL_TYPE, 'DN', BILL_REQ.N_Bill_Amt, -BILL_REQ.N_BILL_AMT))  N_BILL_AMT,
N_PERCENT N_COMM_PCT,
sum(N_PERCENT / 100 * DECODE (BILL_REQ.V_BILL_TYPE, 'DN', BILL_REQ.N_Bill_Amt, -BILL_REQ.N_BILL_AMT)) N_COMM_AMT
from Gnmt_Raise_Bill_Request BILL_REQ , AMMM_QUOT_OTHER_COMM_RATES COM
where  BILL_REQ.V_QUOTATION_ID = COM.V_QUOTATION_ID(+)
AND BILL_REQ.V_PLRI_CODE = COM.V_PLRI_CODE(+)
--and BILL_REQ.V_BILL_NO = 'DN5337173'
GROUP BY  BILL_REQ.V_POLICY_NO, BILL_REQ.V_BILL_NO, BILL_REQ.V_PLRI_CODE,N_PERCENT ,N_PERCENT 
) BILL_REQ_GRP

WHERE     BILL.V_BILL_SOURCE = C.LU_CODE(+)
AND  BILL.V_COMPANY_CODE =  CO.V_COMPANY_CODE 
AND BILL.V_POLICY_NO = BILL_REQ_GRP.V_POLICY_NO (+)
AND BILL.V_BILL_NO = BILL_REQ_GRP.V_BILL_NO(+)
AND BILL.V_POLICY_NO = POL.V_POLICY_NO
AND POL.V_PLAN_CODE = PROD.V_PLAN_CODE
--AND BILL.V_POLICY_NO LIKE ('UG%','UT%')
AND (BILL.V_POLICY_NO LIKE 'UG%' OR BILL.V_POLICY_NO LIKE 'UT%')
AND V_BILL_BAL_TYPE != 'R'
AND V_TRN_TYPE IN ('PYMT', 'RPMT')
--AND V_BILL_SOURCE = 'SGNB'
--and BILL.V_BILL_NO = 'DN5337173'
AND TRUNC (BILL.D_BILL_RAISED_DATE)  BETWEEN ( :P_FROM_DT) AND ( :P_TO_DT)
ORDER BY V_BILL_NO, V_PLRI_CODE