SELECT  D_BIRTH_DATE,/* POLICY.V_POLICY_NO,POL_STATUS.V_STATUS_DESC AS POLICY_STATUS,PLAN.V_PLAN_NAME AS PRODUCT,*/ 
GNMT_CUSTOMER_MASTER.V_NAME AS CUSTOMER, GNDT_CUSTMOBILE_CONTACTS.V_CONTACT_NUMBER
 FROM GNMT_POLICY POLICY  
LEFT JOIN GNMM_PLAN_MASTER PLAN ON POLICY.V_PLAN_CODE = PLAN.V_PLAN_CODE --//plan
LEFT JOIN GNMM_POLICY_STATUS_MASTER POL_STATUS ON POLICY.V_CNTR_STAT_CODE = POL_STATUS.V_STATUS_CODE--//policy status
LEFT JOIN GNMM_POLICY_STATUS_MASTER PRM_STATUS ON POLICY.V_CNTR_PREM_STAT_CODE = PRM_STATUS.V_STATUS_CODE -- //premium status
LEFT JOIN GNMT_CUSTOMER_MASTER ON GNMT_CUSTOMER_MASTER.N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO 
LEFT JOIN GNDT_CUSTMOBILE_CONTACTS ON  GNMT_CUSTOMER_MASTER.N_CUST_REF_NO = GNDT_CUSTMOBILE_CONTACTS.N_CUST_REF_NO --//contacts

WHERE to_char(D_BIRTH_DATE,'MM') = to_char(sysdate, 'MM')--//current month
    AND  to_char(D_BIRTH_DATE,'DD') = to_char(sysdate, 'DD')--//current day 
    AND  POL_STATUS.V_STATUS_DESC IN ('IN-FORCE','LAPSE')
   AND  upper(V_CONTACT_NUMBER) = lower(V_CONTACT_NUMBER)---//switch to get phone numbers(=) only or emails only(!=)
      
GROUP BY POLICY.N_PROPOSER_REF_NO,GNMT_CUSTOMER_MASTER.V_NAME,GNDT_CUSTMOBILE_CONTACTS.V_CONTACT_NUMBER,D_BIRTH_DATE/*,PLAN.V_PLAN_NAME*/
ORDER BY POLICY.N_PROPOSER_REF_NO


/*--Get policy status codes and desc
select * from GNMM_POLICY_STATUS_MASTER
select * from GNMT_CUSTOMER_MASTER 
select * from GNDT_CUSTMOBILE_CONTACTS where N_CUST_REF_NO ='456'
WHERE to_char(D_BIRTH_DATE,'MM') = to_char(sysdate, 'MM')
AND  to_char(D_BIRTH_DATE,'DD') = to_char(sysdate, 'DD')

*/
