SELECT D_BATCH_DATE,N_BATCH_NO,V_JOB_SCRIPT,V_MESSAGE,D_START,N_TIME,D_END 
FROM GNMT_BATCH_EXE_TRACE WHERE TO_CHAR(D_BATCH_DATE,'mm/YYYY') = '02/2021' ORDER BY
D_BATCH_DATE DESC;

select * from GNMT_BATCH_EXE_TRACE order by D_BATCH_DATE desc;

SELECT D_BATCH_DATE,N_BATCH_NO,V_JOB_SCRIPT,V_MESSAGE,D_START,N_TIME,D_END 
FROM GNMT_BATCH_EXE_TRACE WHERE TO_CHAR(D_BATCH_DATE,'mm/YYYY') = '02/2021' ORDER BY
N_TIME DESC;

SELECT D_BATCH_DATE, NUMTODSINTERVAL(SUM(SUBSTR(N_TIME, 1, 2)*3600 + SUBSTR(N_TIME, 4, 2)*60 + SUBSTR(N_TIME, 7, 2)), 'SECOND') TOTAL_DURATION
FROM GNMT_BATCH_EXE_TRACE GROUP BY D_BATCH_DATE ORDER BY D_BATCH_DATE DESC;

SELECT D_BATCH_DATE,N_BATCH_NO,V_JOB_SCRIPT,V_MESSAGE,D_START,N_TIME,D_END FROM GNMT_BATCH_EXE_TRACE 
WHERE TRUNC(D_BATCH_DATE) BETWEEN '01-JAN-2021' AND '31-MAY-2021' AND 
N_BATCH_NO IN ( '10004.8', '7936', '9', '14.1','54','21.002','26') ORDER BY D_BATCH_DATE DESC;

SELECT D_BATCH_DATE,N_BATCH_NO,V_JOB_SCRIPT,V_MESSAGE,D_START,N_TIME,D_END 
FROM GNMT_BATCH_EXE_TRACE WHERE TRUNC(D_BATCH_DATE) BETWEEN '01-JAN-2021' AND '31-MAY-2021' 
AND V_MESSAGE NOT IN ('COMPLETED') ORDER BY D_BATCH_DATE DESC;

SELECT * FROM PSMT_SMS_MESSAGES                                                                                                
WHERE V_SMS_STATUS_CODE != 'S' AND TRUNC (D_CREATED_DATE) BETWEEN '01-JAN-2021' AND '31-MAY-2021' 
AND D_MESG_SENT_DATE IS NOT NULL                                                                                              
ORDER BY D_CREATED_DATE DESC; 

SELECT TO_CHAR(D_MESG_SENT_DATE, 'YYYY-MM-DD') DATE_IDENTIFIED, COUNT(D_MESG_SENT_DATE) NO_SMS
FROM PSMT_SMS_MESSAGES  WHERE TRUNC(D_CREATED_DATE) BETWEEN '01-JAN-2021' AND '31-MAY-2021' 
GROUP BY TO_CHAR(D_MESG_SENT_DATE, 'YYYY-MM-DD')
ORDER BY 1 DESC;

SELECT N_INT_SLNO,V_FUND_CODE,N_BUYING_PRICE,N_SELLING_PRICE,D_LASTUPD_INFTIM FROM INDT_NAV_VALUES
ORDER BY N_INT_SLNO DESC;

SELECT N_INT_SLNO,D_FROM_DATE,D_TO_DATE,D_FORWARD_PRICING_DATE,V_STATUS,D_LASTUPD_INFTIM,V_PRICING_SOURCE,V_UPLOAD,
N_ISF_NAV_SLNO FROM INMT_NAV_VALUES ORDER BY N_INT_SLNO DESC;

SELECT * FROM DBA_JOBS_RUNNING;

SELECT OJB_NAME,OJB_START_DT,OJB_END_DT FROM JHL_OFA_JOBS WHERE OJB_NAME LIKE '%trans%'ORDER BY OJB_START_DT DESC;

SELECT * FROM JHL_OFA_GL_INTERFACE WHERE TRUNC (D_DATE) BETWEEN '01-FEB-2021' AND '31-MAY-2021' 
ORDER BY D_DATE DESC;

SELECT * FROM JHL_OFA_NON_RCT_GL_INTER WHERE TRUNC (D_DATE) BETWEEN '01-FEB-2021' AND '31-MAY-2021'  
ORDER BY D_DATE DESC;

SELECT * FROM JHL_OFA_GL_TRANSACTIONS WHERE TRUNC (D_DATE) BETWEEN '01-FEB-2021' AND '31-MAY-2021'
ORDER BY D_DATE DESC;

select * from GNMM_BATCH_LIST where V_STATUS='A' and V_DAILY_MON_YR ='M' order by V_DAILY_MON_YR desc;