SELECT
(SELECT V_PLAN_NAME FROM GNMM_PLAN_MASTER WHERE V_PLAN_CODE = POLICY.V_PLAN_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY )  PRODUCT,
POL_STATUS.V_STATUS_DESC AS STATUS,
D_ISSUE AS ORIG_POLICY_START_DATE,D_COMMENCEMENT AS EFFECTIVE_DATE, D_POLICY_END_DATE AS  POLICY_END_DATE,POLICY.V_POLICY_NO,N_PROPOSER_REF_NO,
(SELECT V_NAME FROM GNMT_CUSTOMER_MASTER WHERE N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY )  HOLDER_NAME,
(SELECT V_ADD_ONE FROM GNDT_CUSTOMER_ADDRESS WHERE N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO AND V_ADD_CODE ='ADR001' OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY )  RESIDENCE_ADDRESS,
(SELECT V_IDEN_NO FROM GNDT_CUSTOMER_IDENTIFICATION WHERE N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO AND V_IDEN_CODE IN ('PIN','NIC','PP') /*AND V_IDEN_CODE IS NOT NULL*/ ORDER BY V_IDEN_CODE DESC  OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY )  INDENTITY_NO,
(SELECT V_IDEN_CODE FROM GNDT_CUSTOMER_IDENTIFICATION WHERE N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO AND V_IDEN_CODE IN ('PIN','NIC','PP') /*AND V_IDEN_CODE IS NOT NULL*/ ORDER BY V_IDEN_CODE  DESC  OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY )  INDENTITY_TYPE,
--(SELECT V_OCCUP_DESC FROM GNLU_OCCUP_MASTER WHERE V_OCCUP_CODE = POLICY.V_OCCUP_CODE OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY )  OCCUPATION,
(SELECT V_OCCUP_DESC FROM GNLU_OCCUP_MASTER WHERE V_OCCUP_CODE = (SELECT V_OCCUP_CODE FROM GNMT_CUSTOMER_MASTER WHERE N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY) )  OCCUPATION,
(SELECT V_CONTACT_NUMBER FROM GNDT_CUSTMOBILE_CONTACTS WHERE N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO AND V_CONTACT_CODE ='CONT007' OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY )  RESIDENCE_PHONE_NUMBER,
(SELECT V_CONTACT_NUMBER FROM GNDT_CUSTMOBILE_CONTACTS WHERE N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO AND V_CONTACT_CODE ='CONT009' OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY ) OFFICE_PHONE_NUMBER,
(SELECT V_CONTACT_NUMBER FROM GNDT_CUSTMOBILE_CONTACTS WHERE N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO AND V_CONTACT_CODE ='CONT010' OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY ) MOBILE_PHONE_NUMBER,
(SELECT V_CONTACT_NUMBER FROM GNDT_CUSTMOBILE_CONTACTS WHERE N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO AND V_CONTACT_CODE ='CONT003' OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY )  EMAIL,
(SELECT R.V_NATION_DESC FROM GNMT_CUSTOMER_MASTER L LEFT JOIN JHLISFUADM.GNLU_NATIONALITY_MASTER R ON L.V_NATION_CODE = R.V_NATION_CODE WHERE N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY )  NATIONALITY,
 V_UNDERWRITER
 FROM GNMT_POLICY POLICY 
 LEFT JOIN GNMM_POLICY_STATUS_MASTER POL_STATUS ON POLICY.V_CNTR_STAT_CODE = POL_STATUS.V_STATUS_CODE
 WHERE
  V_POLICY_NO NOT LIKE '%UG%' 
  --D_ISSUE >= ADD_MONTHS(TRUNC(SYSDATE), -1)
   --TO_DATE(D_ISSUE,'DD/MM/RRRR') BETWEEN TO_DATE('01-MAR-23','DD/MM/RRRR')  AND TO_DATE('15-MAR-23','DD/MM/RRRR') 
 AND POL_STATUS.V_STATUS_DESC IN ('IN-FORCE')
 --AND POLICY.V_POLICY_NO IN ('UI202300914406','UI202300903324','UI202300909952','UI202300913065')
 --ORDER BY D_ISSUE DESC
 ORDER BY D_ISSUE DESC