DECLARE
V_PASS VARCHAR2(100);
FUNCTION pass(V_INPASSWD VARCHAR2) RETURN varchar2 IS
V_OUTPASSWD VARCHAR2(1000):= '';
LN_CNT1 NUMBER := 0;
LN_SUM  NUMBER := 0;
BEGIN
IF V_INPASSWD IS NOT NULL THEN
LN_CNT1 := LENGTH(RTRIM(LTRIM(V_INPASSWD)));

FOR I IN  1 .. LN_CNT1 LOOP
LN_SUM := LN_SUM + ASCII(SUBSTR(upper(V_INPASSWD),I,1)) ;
END LOOP;
V_OUTPASSWD := V_INPASSWD || LN_SUM;
RETURN(V_OUTPASSWD);
ELSE
RETURN V_INPASSWD;
END IF;
END pass;
BEGIN
  -- SELECT hash_password('INDSHA123') INTO V_PASS FROM DUAL;
  V_PASS:=pass('Rwanda123456$');
  dbms_output.put_line(v_pass);
  --EXECUTE IMMEDIATE 'Alter User ISFADMIN identified by ' || v_pass ;
END;