INSERT INTO APPS.GL_INTERFACE@JICOFPROD.COM (STATUS,
                                                              SET_OF_BOOKS_ID,
                                                              LEDGER_ID,
                                                              USER_JE_SOURCE_NAME,
                                                              USER_JE_CATEGORY_NAME,
                                                              CURRENCY_CODE,
                                                              ACTUAL_FLAG,
                                                              ACCOUNTING_DATE,
                                                              DATE_CREATED,
                                                              CREATED_BY,
                                                              ENTERED_DR,
                                                              ENTERED_CR,
                                                              SEGMENT1,
                                                              SEGMENT2,
                                                              SEGMENT3,
                                                              SEGMENT4,
                                                              SEGMENT5,
                                                              SEGMENT6,
                                                              SEGMENT7,
                                                              SEGMENT8,
                                                              GROUP_ID,
                                                              REFERENCE5,
                                                              REFERENCE10,
                                                              REFERENCE6,
                                                              REFERENCE_DATE,
                                                              REFERENCE1,
                                                              REFERENCE2)
select I.STATUS,
       I.SET_OF_BOOKS_ID,
       I.SET_OF_BOOKS_ID,
       TRIM (I.USER_JE_SOURCE_NAME),
       TRIM (I.USER_JE_CATEGORY_NAME),
       I.CURRENCY_CODE,
       I.ACTUAL_FLAG,
       SYSDATE,
       I.DATE_CREATED,
       I.CREATED_BY,
       I.ENTERED_DR,
       I.ENTERED_CR,
       I.SEGMENT1,
       I.SEGMENT2,
       I.SEGMENT3,
       I.SEGMENT4,
       I.SEGMENT5,
       I.SEGMENT6,
       I.SEGMENT7,
       I.SEGMENT8,
       I.GROUP_ID,
       I.REFERENCE5,
       I.REFERENCE10,
       I.REFERENCE6,
       I.REFERENCE_DATE,
       I.REFERENCE1,
       I.REFERENCE2 from (SELECT * FROM JHL_OFA_GL_INTERFACE where REFERENCE1 in ('HQ220196648')) I;
COMMIT;

