DESC GNMT_POLICY;

SELECT V_POLICY_NO,D.V_CNTR_STAT_CODE,D.N_SUM_COVERED,D.D_COMMENCEMENT,
D.V_STATUS FROM GNMT_POLICY WHERE V_CNTR_STAT_CODE IN ('NB024');


SELECT B.D_FROM, A.V_POLICY_NO,A.D_REVIVE,A.V_REVIVAL_TYPE, D.V_CNTR_STAT_CODE,D.N_SUM_COVERED,D.D_COMMENCEMENT,

D.V_STATUS FROM PSMT_POLICY_REVIVAL A, GN_CONTRACT_STATUS_LOG B, GNMT_POLICY D WHERE A.v_policy_no IN (SELECT C.V_POLICY_NO FROM GNMT_POLICY C  WHERE C.V_CNTR_STAT_CODE IN ('NB024')) 

AND TO_DATE(D_REVIVE,'DD/MM/RRRR') BETWEEN TO_DATE('01-JAN-21','DD/MM/RRRR')  AND TO_DATE('31-MAR-22','DD/MM/RRRR')

AND 

A.V_POLICY_NO = B.V_POLICY_NO

AND A.V_POLICY_NO = D.V_POLICY_NO

AND B.V_CURR_STAT_CODE='NB024';


SELECT * FROM GNMM_POLICY_STATUS_MASTER WHERE V_STATUS_CODE IN ('NB024'); 

SELECT V_POLICY_NO from GNMT_POLICY where; 

SELECT * FROM GN_CONTRACT_STATUS_LOG WHERE V_POLICY_NO IN (SELECT V_POLICY_NO FROM GNMT_POLICY WHERE V_CNTR_STAT_CODE IN ('NB024'))
AND V_CURR_STAT_CODE='NB024';