JHL_OFA_UTILS_UPDATED.CREATE_INDIVIDUAL_SUPPLIER_NEW


/*back up data before deleting on staging table*/

XXJICUG_AP_SUPPLIER_STG@JICOFPROD.COM
XXJICUG_AP_SUPPLIER_SITE_STG@JICOFPROD.COM
 XXJICUG_AP_SUPPLIER_CONCT_STG@JICOFPROD.COM;
 
 
 
-- CREATE TABLE JHL_AP_SUPPLIER_STG_BK AS
 SELECT *
 FROM XXJICUG_AP_SUPPLIER_STG@JICOFPROD.COM
WHERE PAY_GROUP LIKE '%LIFE%'
and  LEGACY_REF1 LIKE 'XUGL%'
AND PROCESS_FLAG IN ('1','3') 
ORDER BY 6 DESC;

 

-- CREATE TABLE JHL_AP_SUPPLIER_SITE_STG_BK AS
SELECT *
FROM XXJICUG_AP_SUPPLIER_SITE_STG@JICOFPROD.COM
WHERE PAY_GRP_LKP_CODE  LIKE '%LIFE%';




-- CREATE TABLE JHL_AP_SUPPLIER_CONCT_STG_BK AS
 
 SELECT *
FROM XXJICUG_AP_SUPPLIER_CONCT_STG@JICOFPROD.COM B
WHERE  B.LEGACY_REF1 IN (SELECT A.LEGACY_REF1
                                   FROM XXJICUG_AP_SUPPLIER_STG@JICOFPROD.COM A);






COMMIT;