
JHL_OFA_UTILS.JHL_OFA_PAYABLES_PROC;
JHL_OFA_UTILS.JHL_OFA_TRANSFORM_GL_VOU

JHL_OFA_UTILS.create_ofa_cancelled_pymt_gl
JHL_OFA_UTILS.transform_ofa_cancel_py_trans
JHL_OFA_UTILS.transform_ofa_py_gl_trans
JHL_OFA_UTILS.SEND_PYMT_GL_TRANS_TO_OFA;

SELECT V_GL_CODE ACCT_CODE,V_PROCESS_CODE, sum(decode(V_TYPE,'D',-N_SOURCE_AMOUNT,N_SOURCE_AMOUNT)) AMOUNT, decode(V_DESC,'INCOME_TAX','WHT TAX',V_DESC)  V_DESC,

                         (SELECT DISTINCT  OFA_ACC_CODE 
                                             FROM JHL_ISF_OFA_ACC_MAP
                                             WHERE TRIM(ISF_GL_CODE) = TRIM(D.V_GL_CODE)
                                             and TRIM(ACC_DESC) = TRIM(d.V_DESC))  OFA_ACC_CODE,   decode( sign(sum(decode(V_TYPE,'D',-N_SOURCE_AMOUNT,N_SOURCE_AMOUNT))),-1,1,2) ORD,
                         V_DOCU_REF_NO V_VOU_NO,BPG_FINANCE_BATCHES.BFN_GET_PAYEE_NAME(V_DOCU_REF_NO) VENDOR_NAME,
                        ABS( sum(decode(V_TYPE,'D',-N_SOURCE_AMOUNT,N_SOURCE_AMOUNT)) ) AMT,N_CONVERSION_RATE
                 
--2021000893, 2020006544,2021000944
FROM GNMT_GL_MASTER M,GNDT_GL_DETAILS D
WHERE M.N_REF_NO = D.N_REF_NO
AND M.V_JOURNAL_STATUS = 'C'
AND V_DOCU_TYPE='VOUCHER'
AND V_DOCU_REF_NO = '2021000893'
and V_DESC  NOT LIKE  ('%PAYMENT CONTROL%') 
group by  V_GL_CODE,V_PROCESS_CODE,V_DESC,V_DOCU_REF_NO,N_CONVERSION_RATE
ORDER BY ORD,AMT DESC;



DECLARE

CURSOR VOUCHERS IS 

SELECT  V_VOU_DESC,V_VOU_NO,D_VOU_DATE
FROM PYMT_VOUCHER_ROOT PM, PYMT_VOU_MASTER PV
WHERE PM.V_MAIN_VOU_NO = PV.V_MAIN_VOU_NO
AND TO_DATE(D_VOU_DATE,'DD/MM/RRRR')   BETWEEN TO_DATE('01-JAN-21','DD/MM/RRRR')  AND TO_DATE(sysdate,'DD/MM/RRRR')
AND JHL_GEN_PKG.IS_VOUCHER_AUTHORIZED(V_VOU_NO) = 'Y'
AND JHL_GEN_PKG.IS_VOUCHER_CANCELLED (V_VOU_NO) = 'N'
AND  V_VOU_NO NOT IN (SELECT V_VOU_NO FROM JHL_OFA_PYMT_TRANSACTIONS);
--AND V_VOU_NO in ('2021000893');
 

BEGIN

     FOR I IN VOUCHERS LOOP
                
                 JHL_OFA_UTILS.JHL_OFA_TRANSFORM_GL_VOU(I.V_VOU_NO);
                 commit;
       END LOOP;

END;



and V_DESC     <> 'PAYMENT CONTROL  ACCOUNT' ;
PAYMENT CONTROL  ACCOUNT
PAYMENT CONTROL

 

select *
from JHL_OFA_JOBS
where  OJB_NAME = 'JHL_OFA_PAYABLES_PROC'
order by 1 desc;

select *
from JHL_OFA_GL_PYMT_TRANS
where V_DOCU_REF_NO='2021000893';

select *
from JHL_OFA_PYMT_GL_INTER
where REFERENCE1 ='2021000893';

delete from JHL_OFA_GL_PYMT_TRANS;
delete from JHL_OFA_PYMT_GL_INTER;



    SELECT OGLI_NO, STATUS, SET_OF_BOOKS_ID, USER_JE_SOURCE_NAME, USER_JE_CATEGORY_NAME, CURRENCY_CODE, ACTUAL_FLAG, 
    ACCOUNTING_DATE, DATE_CREATED, CREATED_BY, ENTERED_DR, ENTERED_CR, SEGMENT1, SEGMENT2, SEGMENT3, SEGMENT4, SEGMENT5, 
    SEGMENT6, SEGMENT7, SEGMENT8, GROUP_ID, JOURNAL_DESCRIPTION, LINE_DESCRIPTION, to_char(REFERENCE) REFERENCE, REFERENCE_DATE, REFERENCE1, 
    REFERENCE2, N_REF_NO, V_BRANCH_CODE, V_LOB_CODE, 
    V_PROCESS_CODE, REFERENCE5, REFERENCE6, REFERENCE10, OGLI_PROCESSED, V_DOCU_TYPE, OFA_VGL_NO, OFA_VGL_CODE, OGLI_POSTED, D_DATE
    FROM JHL_OFA_PYMT_GL_INTER
       WHERE 1=1
--    AND N_REF_NO = v_n_ref_no
    AND OGLI_PROCESSED = 'Y'
    AND OGLI_POSTED =  'N'
    ORDER BY REFERENCE1 ;
    
    
    
   exec JHL_OFA_UTILS.SEND_PYMT_GL_TRANS_TO_OFA;
   
   
   
  select *
  from  APPS.gl_interface@JICOFPROD.COM
  where 1=1
  
  --REFERENCE1 = '2021000294'
  AND CURRENCY_CODE =      'UGX'

   
    AND USER_JE_CATEGORY_NAME  = 'ISF Payments'  ;
      ORDER BY DATE_CREATED DESC;
      
      
       TO_CHAR(SYSDATE,'DD-MON-YY');
       DESC APPS.gl_interface@JICOFPROD.COM;
       
       UPDATE APPS.gl_interface@JICOFPROD.COM
       SET DATE_CREATED = TRUNC(SYSDATE)
       WHERE   CURRENCY_CODE =      'UGX'

   
    AND USER_JE_CATEGORY_NAME  = 'ISF Payments'  ;
    
    COMMIT;
    
    BEGIN
    JHL_OFA_UTILS.SEND_PYMT_GL_TRANS_TO_OFA;
    COMMIT;
    END;