select A.V_POLICY_NO,D.V_PROPOSER_NAME, A.N_AGENT_NO,A.D_COMM_GEN,A.D_RECEIPT,A.N_COMM_AMT, A.N_COMM_YEAR, A.V_RECEIPT_NO, A.V_EARNED_RANK

from AMMT_POL_COMM_DETAIL A, GNMT_POLICY D
where TO_DATE(D_COMM_GEN,'DD/MM/RRRR')   BETWEEN TO_DATE('22-DEC-22','DD/MM/RRRR')  AND TO_DATE('31-DEC-22','DD/MM/RRRR')
AND D.V_POLICY_NO=A.V_POLICY_NO
; 
SELECT * FROM  AMMT_POL_COMM_DETAIL  WHERE  V_POLICY_NO IN ('CL4167') ORDER BY D_COMM_GEN DESC;
select B.N_AGENT_NO,B.V_AGENT_CODE,B.N_CUST_REF_NO, C.V_NAME from AMMM_AGENT_MASTER B, GNMT_CUSTOMER_MASTER C
WHERE C.N_CUST_REF_NO=B.N_CUST_REF_NO;

SELECT C.V_NAME,C.N_CUST_REF_NO  FROM GNMT_CUSTOMER_MASTER C;
SELECT D.V_POLICY_NO, D.V_PROPOSER_NAME FROM GNMT_POLICY D;

SELECT * FROM AMMT_POL_COMM_DETAIL WHERE /*V_POLICY_NO LIKE ('UI201700259456')*/ 
  TO_DATE(D_COMM_GEN,'DD/MM/RRRR')   BETWEEN TO_DATE('01-JAN-23','DD/MM/RRRR')  AND TO_DATE('31-JAN-23','DD/MM/RRRR')
  AND V_COMM_STATUS NOT IN ('P')
 ORDER BY D_COMM_GEN DESC;

SELECT * FROM AMMT_POL_COMM_DETAIL WHERE V_POLICY_NO LIKE ('UI202200847015');
;