

SELECT 
W.N_AGENT_NO, 
(SELECT  V_VOU_NO FROM  PYMT_VOU_MASTER WHERE V_IND_COMPANY ='C' AND V_PAYEE_TYPE='AG' AND V_COMPANY_CODE =V_COMPANY_CODE AND ROWNUM =1) VOUCHER_NUMBER,
(SELECT  N_VOU_AMOUNT FROM  PYMT_VOU_MASTER WHERE V_IND_COMPANY ='C' AND V_PAYEE_TYPE='AG' AND V_COMPANY_CODE =V_COMPANY_CODE AND ROWNUM =1) Amount,
(SELECT  V_PAYEE_NAME FROM  PYMT_VOU_MASTER WHERE V_IND_COMPANY ='C' AND V_PAYEE_TYPE='AG' AND V_COMPANY_CODE =V_COMPANY_CODE and rownum =1) Payee_name,
W.V_POLICY_NO, 
X.V_COMPANY_CODE 
FROM AMMT_POL_AG_COMM W , AMMM_AGENT_MASTER X WHERE W.N_AGENT_NO = X.N_AGENT_NO
AND W.V_POLICY_NO='UG201700254475'
AND V_ROLE_CODE='SELLING';

select * from   AMMM_AGENT_MASTER where  V_COMPANY_CODE = '002SARAH'
;
SELECT * FROM PYMT_VOU_MASTER WHERE V_VOU_NO ='2017005938';


SELECT * FROM 
(
SELECT 
W.N_AGENT_NO, 
(SELECT  V_VOU_NO FROM  PYMT_VOU_MASTER WHERE  V_IND_COMPANY ='C'  AND  V_PAYEE_TYPE='AG' AND V_COMPANY_CODE =X.V_COMPANY_CODE AND ROWNUM =1) VOUCHER_NUMBER,
(SELECT  N_VOU_AMOUNT FROM  PYMT_VOU_MASTER WHERE V_IND_COMPANY ='C'  AND V_PAYEE_TYPE='AG' AND V_COMPANY_CODE =X.V_COMPANY_CODE AND ROWNUM =1) Amount,
(SELECT  V_PAYEE_NAME FROM  PYMT_VOU_MASTER WHERE V_IND_COMPANY ='C'  AND V_PAYEE_TYPE='AG' AND V_COMPANY_CODE =X.V_COMPANY_CODE and rownum =1) Payee_name,
--(SELECT  V_PAYEE_NAME FROM PYMT_VOU_MASTER  where V_COMPANY_CODE =  
W.V_POLICY_NO, 
X.V_COMPANY_CODE 
FROM AMMM_AGENT_MASTER X, AMMT_POL_AG_COMM W WHERE W.N_AGENT_NO = X.N_AGENT_NO
AND W.V_POLICY_NO IN (SELECT V_POLICY_NO FROM AMMT_POL_AG_COMM)
AND V_ROLE_CODE='SELLING'
)  WHERE PAYEE_NAME IS NOT NULL 
AND   PAYEE_NAME NOT IN ('THE JUBILEE INSURANCE COMPANY OF UGANDA LIMITED')
/*and V_COMPANY_CODE not in ('NIL')*/
AND V_POLICY_NO LIKE ('UG%')
ORDER BY VOUCHER_NUMBER DESC;