
you normally create/add/amend roles  and attach screen details here

SELECT * FROM GNDT_ROLE_PROG WHERE V_ROLE_NAME='RFORALLOBJECTS'; -- roLES WITH THEIR PROGRAMS 

SELECT * FROM GNDT_ROLE_PROG WHERE V_PROG_ID='AM_FRM_24'; -- roLES WITH THEIR PROGRAMS 

SELECT * FROM GNDT_USER_PROG_EXCEPTION WHERE V_PROG_ID='AM_FRM_24';

SELECT * FROM  GNDT_UM_USER_PRIVS_TASK ORDER BY N_TASK_ID DESC; --ASSIGN USER TO ROLES IN THIS TABLE 

SELECT V_PROG_ID,V_PROG_DESC FROM  GNLU_PROG_MASTER; where V_PROG_DESC IN ('CALLING'); -- ALL PROGRAMS

SELECT * FROM  jhl_role  WHERE V_ROLE_NAME IN ('R205'); -- for reporting purpose, HAS ALL ROLES
SELECT * FROM JHL_USER_ROLE;
select * from role_master;
edit jhl_role;

SELECT * FROM GNDT_UM_ROLE_TASK;

EDIT GNDT_UM_USER_PRIVS_TASK;

SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE='RSONKO';
revoke RFORALLOBJECTS, RNORMAL,CONNECT,RESOURCE,SELECT_CATALOG_ROLE from ALUYINDA;
SELECT * FROM  GNDT_UM_USER_PRIVS_TASK ORDER BY N_TASK_ID DESC;
GRANT CONNECT,RESOURCE,RFORALLOBJECTS TO PAMPUMUZA;
SELECT * FROM  GNDT_UM_USER_PRIVS_TASK WHERE V_USER_NAME IN ('ATWINAMATSIKO');
REVOKE SELECT_CATALOG_ROLE,RNORMAL FROM ATWINAMATSIKO;

GRANT R205 TO MNAMISANGO;

R205
R210
R226
RFORALLOBJECTS
RNORMAL