
select V_POLICY_NO,D_DISPATCH_DATE,D_ISSUE, V_AGENT_CODE,V_PROPOSER_NAME from gnmt_policy
where   TO_DATE(D_ISSUE,'DD/MM/RRRR')   BETWEEN TO_DATE('01-JAN-23','DD/MM/RRRR')  AND TO_DATE(SYSDATE,'DD/MM/RRRR');

select * from gnmt_policy where V_POLICY_NO='UI202300943051';