
    SELECT OGLI_NO, STATUS, SET_OF_BOOKS_ID, USER_JE_SOURCE_NAME, USER_JE_CATEGORY_NAME, CURRENCY_CODE, ACTUAL_FLAG, 
    ACCOUNTING_DATE, DATE_CREATED, CREATED_BY, ENTERED_DR, ENTERED_CR, SEGMENT1, SEGMENT2, SEGMENT3, SEGMENT4, SEGMENT5, 
    SEGMENT6, SEGMENT7, SEGMENT8, GROUP_ID, JOURNAL_DESCRIPTION, LINE_DESCRIPTION, to_char(REFERENCE) REFERENCE, REFERENCE_DATE, REFERENCE1, 
    REFERENCE2, N_REF_NO, V_BRANCH_CODE, V_LOB_CODE, 
    V_PROCESS_CODE, REFERENCE5, REFERENCE6, REFERENCE10, OGLI_PROCESSED, V_DOCU_TYPE, OFA_VGL_NO, OFA_VGL_CODE, OGLI_POSTED, D_DATE
    FROM JHL_OFA_PYMT_GL_INTER
       WHERE 1=1
--    AND N_REF_NO = v_n_ref_no
    AND OGLI_PROCESSED = 'Y'
    AND OGLI_POSTED =  'N'
    ORDER BY REFERENCE1 ;