select N_CUST_REF_NO,V_NAME,D_BIRTH_DATE,V_SEX from GNMT_CUSTOMER_MASTER;

select  N_AGENT_NO,V_AGENT_CODE,N_CUST_REF_NO from AMMM_AGENT_MASTER;

select N_CUST_REF_NO,V_CONTACT_NUMBER from GNDT_CUSTMOBILE_CONTACTS;


desc AMMM_AGENT_MASTER;  N_AGENT_NO,V_AGENT_CODE,N_CUST_REF_NO


desc GNMT_CUSTOMER_MASTER;N_CUST_REF_NO,V_NAME,D_BIRTH_DATE,V_SEX,

desc GNDT_CUSTMOBILE_CONTACTS; N_CUST_REF_NO,V_CONTACT_NUMBER;

select  AMMM_AGENT_MASTER.N_CUST_REF_NO,N_AGENT_NO, V_AGENT_CODE, V_NAME,D_BIRTH_DATE,V_SEX,V_CONTACT_NUMBER from AMMM_AGENT_MASTER LEFT JOIN 
GNMT_CUSTOMER_MASTER ON GNMT_CUSTOMER_MASTER.N_CUST_REF_NO = AMMM_AGENT_MASTER.N_CUST_REF_NO LEFT JOIN
GNDT_CUSTMOBILE_CONTACTS ON  AMMM_AGENT_MASTER.N_CUST_REF_NO = GNDT_CUSTMOBILE_CONTACTS.N_CUST_REF_NO;


/*V_POLICY_NO, V_PYMT_FREQ , V_PLAN_CODE, N_SUM_COVERED,N_CONTRIBUTION, V_QUOTATION_ID,D_PROPOSAL_DATE, D_PROPOSAL_SUBMIT,D_COMMENCEMENT,D_NEXT_OUT_DATE,D_POLICY_END_DATE
N_PROPOSER_REF_NO,N_PREM_PAY_TERM,D_PREM_PAYING_END_DATE, V_CNTR_PREM_STAT_CODE,N_REQUEST_SA, V_PROPOSER_NAME, V_PAYER_NAME*/
SELECT  POLICY.V_POLICY_NO, GNMT_CUSTOMER_MASTER.V_NAME AS CUSTOMER, PLAN.V_PLAN_NAME AS PRODUCT, GNMT_CUSTOMER_MASTER.D_BIRTH_DATE,GNMT_CUSTOMER_MASTER.V_SEX,GNDT_CUSTMOBILE_CONTACTS.V_CONTACT_NUMBER  FROM GNMT_POLICY POLICY  
LEFT JOIN GNMM_PLAN_MASTER PLAN ON POLICY.V_PLAN_CODE = PLAN.V_PLAN_CODE  LEFT JOIN
GNMT_CUSTOMER_MASTER ON GNMT_CUSTOMER_MASTER.N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO LEFT JOIN
GNDT_CUSTMOBILE_CONTACTS ON  GNMT_CUSTOMER_MASTER.N_CUST_REF_NO = GNDT_CUSTMOBILE_CONTACTS.N_CUST_REF_NO
WHERE GNMT_CUSTOMER_MASTER.V_SEX IN ('F') ;

