---staging table for ISF vochers---
--delete 
select *
 FROM JHL_OFA_PYMT_TRANSACTIONS
where V_VOU_NO = '2021000229';   

SELECT *
FROM JHL_OFA_PYMT_TRANSACTIONS
where V_VOU_NO = '2020036843';      


SELECT  * --DISTINCT VOUCHER_NUM
  FROM XXJICUG_AP_INVOICES_STG@JICOFPROD.COM 
WHERE OPERATING_UNIT = 'JHL_UG_LIF_OU'
AND PROCESS_FLAG  in ( '1')
AND VOUCHER_NUM  in ('2020036843');
--and GL_DATE is null;




SELECT * 
FROM APPS.XXJIC_AP_CLAIM_MAP@JICOFPROD.COM
WHERE PAYMENT_VOUCHER like  '%2021000226%' 
and  LOB_NAME =  'JHL_UG_LIF_OU'; 

SELECT * 
FROM JHL_OFA_PYMT_TRANSACTIONS
WHERE V_VOU_NO= '2018089524';

SELECT  VOUCHER_NUM,  ' : In Staging table' DESCRIPTION
FROM XXJICUG_AP_INVOICES_STG@JICOFPROD.COM 
WHERE OPERATING_UNIT = 'JHL_UG_LIF_OU'
--AND PROCESS_FLAG  in ( '1','3')
AND VOUCHER_NUM  IN ('2020036986')
UNION ALL 
SELECT  PAYMENT_VOUCHER, ': Already In Oracle' DESCRIPTION
FROM APPS.XXJIC_AP_CLAIM_MAP@JICOFPROD.COM
WHERE LOB_NAME =  'JHL_UG_LIF_OU'
and PAYMENT_VOUCHER  IN ('2020036986')

UNION ALL 

SELECT V_VOU_NO, OVE_DESC
FROM JHL_OFA_VOUCHER_ERRORS
WHERE V_VOU_NO   IN ('2020008588'); 


SELECT * 
FROM  APPS.XXJIC_AP_SUPPLIER_MAP@JICOFPROD.COM
WHERE PIN_NO = 'A006274080S'; 

2655583
2651940
2655583

select rowid,gndt_customer_identification.*
from gndt_customer_identification
where V_IDEN_CODE ='PIN'
and N_CUST_REF_NO = 2651940
AND V_IDEN_NO = 'A009264110C'; 

select *
from gnmt_customer_master
where N_CUST_REF_NO = 2651940;

select  N_PROPOSER_REF_NO,N_PAYER_REF_NO
from gnmt_policy
where v_policy_no = 'IL201801439744';

SELECT *
FROM PSDT_ALTERATION_HISTORY
WHERE N_ALTERATION_SEQ_NO ='418689' ;

exec JHL_OFA_UTILS_UPDATED.CREATE_INDIVIDUAL_SUPPLIER_NEW(2655583);

exec JHL_OFA_UTILS_UPDATED.CREATE_CORPORATE_SUPPLIER_NEW('1000478','HO');





SELECT *
 FROM  XXJIC_AP_SUPPLIER_STG@JICOFPROD.COM 
WHERE PAY_GROUP  IN  ('LIFE-CLAIM','LIFE-COMMISSION')
AND LEGACY_REF1 = 'XKEL107350I';

SELECT *
 FROM XXJIC_AP_SUPPLIER_SITE_STG@JICOFPROD.COM
WHERE PAY_GRP_LKP_CODE  IN  ('LIFE-CLAIM','LIFE-COMMISSION')
AND /*VENDOR_SITE_CODE =  J.VENDOR_SITE_CODE
AND*/ OPERATING_UNIT ='JHL_UG_LIF_OU'
AND LEGACY_REF1 = 'XKEL196C';





DELETE FROM JHL_OFA_PYMT_TRANSACTIONS
WHERE V_VOU_NO IN (
                        SELECT  VOUCHER_NUM
                        FROM XXJICUG_AP_INVOICES_STG@JICOFPROD.COM 
                        WHERE OPERATING_UNIT = 'JHL_UG_LIF_OU'
                  --      AND VOUCHER_NUM  in ('2017085338','2017086205')
                        AND PROCESS_FLAG in ( '1','3'));
                        
DELETE 
FROM  JHL_OFA_PYMT_VOUCHER_DTLS
WHERE V_VOU_NO IN (   SELECT  VOUCHER_NUM
                                        FROM XXJICUG_AP_INVOICES_STG@JICOFPROD.COM 
                                        WHERE OPERATING_UNIT = 'JHL_UG_LIF_OU'
--                                            AND VOUCHER_NUM  in ('2017085338','2017086205')
                                        AND PROCESS_FLAG in ( '1','3'));
                        
delete 
FROM XXJICUG_AP_INVOICES_STG@JICOFPROD.COM 
WHERE OPERATING_UNIT = 'JHL_UG_LIF_OU'
--    AND VOUCHER_NUM  in ('2018007980')
AND PROCESS_FLAG in ( '1','3');

update  XXJICUG_AP_INVOICES_STG@JICOFPROD.COM 
set ERROR_MESSAGE = null,
    PROCESS_FLAG = '1'   
WHERE OPERATING_UNIT = 'JHL_UG_LIF_OU'
3
AND PROCESS_FLAG in ( '1','3');


delete FROM JHL_OFA_PYMT_TRANSACTIONS
WHERE V_VOU_NO  not IN 
(
SELECT  PAYMENT_VOUCHER
 FROM APPS.XXJIC_AP_CLAIM_MAP@JICOFPROD.COM
 WHERE LOB_NAME = 'JHL_UG_LIF_OU'
 )
 

 delete from JHL_OFA_PYMT_VOUCHER_DTLS
 WHERE V_VOU_NO  not IN 
(
SELECT  PAYMENT_VOUCHER
 FROM APPS.XXJIC_AP_CLAIM_MAP@JICOFPROD.COM
 WHERE LOB_NAME = 'JHL_UG_LIF_OU'
 );




  

EXEC JHL_OFA_UTILS.JHL_OFA_PAYABLES_PROC;

JHL_OFA_UTILS.JHL_OFA_PAYABLES_PROC;


DECLARE

CURSOR VOUCHERS IS 

SELECT  V_VOU_DESC,V_VOU_NO,D_VOU_DATE
FROM PYMT_VOUCHER_ROOT PM, PYMT_VOU_MASTER PV
WHERE PM.V_MAIN_VOU_NO = PV.V_MAIN_VOU_NO
--AND TO_DATE(JHL_GEN_PKG.GET_VOUCHER_APPROVAL_DATE(V_VOU_NO),'DD/MM/RRRR') BETWEEN TO_DATE('01-JUL-17','DD/MM/RRRR')  AND TO_DATE(SYSDATE,'DD/MM/RRRR')
AND TO_DATE(D_VOU_DATE,'DD/MM/RRRR')   BETWEEN TO_DATE('01-JAN-20','DD/MM/RRRR')  AND TO_DATE(sysdate,'DD/MM/RRRR')
AND JHL_GEN_PKG.IS_VOUCHER_AUTHORIZED(V_VOU_NO) = 'Y'
AND  V_VOU_NO NOT IN (SELECT V_VOU_NO FROM JHL_OFA_PYMT_TRANSACTIONS)
--AND JHL_BI_UTILS.is_voucher_annuity ('V_VOU_NO') = 'N'
--AND JHL_GEN_PKG.IS_VOUCHER_CANCELLED(V_VOU_NO) = 'N'
--and V_VOU_DESC <>  'COMMISSION';
and V_VOU_NO in ('2020036843');
--and V_VOU_NO = :v_voucher_no ;

BEGIN

     FOR I IN VOUCHERS LOOP
                
                 JHL_OFA_UTILS_UPDATED.JHL_OFA_TRANSFORM_GL_VOU(I.V_VOU_NO);
                 commit;
       END LOOP;

END;

JHL_OFA_UTILS_UPDATED.CREATE_EFT_PYMT_TRANS_MASTER

SELECT *
FROM GNMT_GL_MASTER M,GNDT_GL_DETAILS D
WHERE M.N_REF_NO = D.N_REF_NO
AND M.V_JOURNAL_STATUS = 'C'
AND V_DOCU_TYPE='VOUCHER'
 AND V_DOCU_REF_NO in (

SELECT  V_VOU_NO
FROM PYMT_VOUCHER_ROOT PM, PYMT_VOU_MASTER PV
WHERE PM.V_MAIN_VOU_NO = PV.V_MAIN_VOU_NO
AND TO_DATE(D_VOU_DATE) BETWEEN TO_DATE('01-JUL-17','DD/MM/RRRR')  AND TO_DATE('20-AUG-17','DD/MM/RRRR')
 AND JHL_GEN_PKG.IS_VOUCHER_AUTHORIZED(V_VOU_NO) = 'Y'
AND  V_VOU_NO NOT IN (SELECT V_VOU_NO FROM JHL_OFA_PYMT_TRANSACTIONS)
);

SELECT *
FROM APPS.XXJIC_AP_CLAIM_MAP@JICOFPROD.COM
WHERE LOB_NAME = 'JHL_UG_LIF_OU'
AND PAYMENT_AMOUNT IS  NULL 
AND  PAYMENT_VOUCHER = '2017027192';


SELECT *
FROM XXJICUG_AP_INVOICES_STG@JICOFPROD.COM 
WHERE OPERATING_UNIT= 'JHL_UG_LIF_OU'
and VOUCHER_NUM = :v_voucher_no ; 


900002-NATION CENTRE

select *
from GNMT_CUSTOMER_MASTER
where N_CUST_REF_NO = 1241869

select * 
from GNMM_COMPANY_MASTER C
WHERE C.V_Company_Code = '900002'
AND C.V_Company_Branch = 'NATION CENTRE';



SELECT *
--INTO v_post_count
--INTO v_pol_type, v_pol_no
FROM GNMT_GL_MASTER M,GNDT_GL_DETAILS D
WHERE M.N_REF_NO = D.N_REF_NO
AND M.V_JOURNAL_STATUS = 'C'
--AND NVL(M.V_REMARKS,'N')!='X'
AND V_DOCU_TYPE='VOUCHER'
--AND V_DOCU_REF_NO = '2016084503'
--2017005999
 AND V_DOCU_REF_NO = :v_voucher_no;


SELECT *
--INTO vou_count
FROM JHL_OFA_PYMT_TRANSACTIONS
WHERE V_VOU_NO = :v_voucher_no;



select *
from SUN_EXPORT_VOU
where SUN_DRCR_DOC_NO = '2017027192';


SELECT  *
FROM JLF_A_SALFLDG@SUN.COM
WHERE TREFERENCE = '2017027192';

----------------------------

SELECT  V_VOU_DESC,V_VOU_NO,D_VOU_DATE
FROM PYMT_VOUCHER_ROOT PM, PYMT_VOU_MASTER PV
WHERE PM.V_MAIN_VOU_NO = PV.V_MAIN_VOU_NO
--AND TO_DATE(JHL_GEN_PKG.GET_VOUCHER_APPROVAL_DATE(V_VOU_NO),'DD/MM/RRRR') BETWEEN TO_DATE('01-JUL-17','DD/MM/RRRR')  AND TO_DATE(SYSDATE,'DD/MM/RRRR')
AND TO_DATE(D_VOU_DATE,'DD/MM/RRRR')   BETWEEN TO_DATE('01-JUL-17','DD/MM/RRRR')  AND TO_DATE('31-AUG-17','DD/MM/RRRR')
-- AND JHL_GEN_PKG.IS_VOUCHER_AUTHORIZED(V_VOU_NO) = 'Y'
 and  V_VOU_NO not in (
--AND  V_VOU_NO NOT IN (SELECT V_VOU_NO FROM JHL_OFA_PYMT_TRANSACTIONS)


SELECT PAYMENT_VOUCHER
FROM APPS.XXJIC_AP_CLAIM_MAP@JICOFPROD.COM
WHERE LOB_NAME = 'JHL_UG_LIF_OU');


delete 
from JHL_OFA_PYMT_VOUCHER_DTLS
where  V_VOU_NO in (

SELECT  V_VOU_NO
FROM PYMT_VOUCHER_ROOT PM, PYMT_VOU_MASTER PV
WHERE PM.V_MAIN_VOU_NO = PV.V_MAIN_VOU_NO
--AND TO_DATE(JHL_GEN_PKG.GET_VOUCHER_APPROVAL_DATE(V_VOU_NO),'DD/MM/RRRR') BETWEEN TO_DATE('01-JUL-17','DD/MM/RRRR')  AND TO_DATE(SYSDATE,'DD/MM/RRRR')
AND TO_DATE(D_VOU_DATE,'DD/MM/RRRR')   BETWEEN TO_DATE('01-JUL-17','DD/MM/RRRR')  AND TO_DATE(sysdate,'DD/MM/RRRR')
-- AND JHL_GEN_PKG.IS_VOUCHER_AUTHORIZED(V_VOU_NO) = 'Y'
 and  V_VOU_NO not in (
SELECT PAYMENT_VOUCHER
FROM APPS.XXJIC_AP_CLAIM_MAP@JICOFPROD.COM
WHERE LOB_NAME = 'JHL_UG_LIF_OU')

);


DELETE FROM JHL_OFA_PYMT_TRANSACTIONS
WHERE V_VOU_NO IN (

SELECT  V_VOU_NO
FROM PYMT_VOUCHER_ROOT PM, PYMT_VOU_MASTER PV
WHERE PM.V_MAIN_VOU_NO = PV.V_MAIN_VOU_NO
--AND TO_DATE(JHL_GEN_PKG.GET_VOUCHER_APPROVAL_DATE(V_VOU_NO),'DD/MM/RRRR') BETWEEN TO_DATE('01-JUL-17','DD/MM/RRRR')  AND TO_DATE(SYSDATE,'DD/MM/RRRR')
AND TO_DATE(D_VOU_DATE,'DD/MM/RRRR')   BETWEEN TO_DATE('01-JUL-17','DD/MM/RRRR')  AND TO_DATE(sysdate,'DD/MM/RRRR')
-- AND JHL_GEN_PKG.IS_VOUCHER_AUTHORIZED(V_VOU_NO) = 'Y'
 and  V_VOU_NO not in (
SELECT PAYMENT_VOUCHER
FROM APPS.XXJIC_AP_CLAIM_MAP@JICOFPROD.COM
WHERE LOB_NAME = 'JHL_UG_LIF_OU')
);


delete 
FROM XXJICUG_AP_INVOICES_STG@JICOFPROD.COM 
WHERE OPERATING_UNIT = 'JHL_UG_LIF_OU'
--    AND VOUCHER_NUM  in ('2017085338','2017086205')
AND PROCESS_FLAG in ( '1','3');





•    2018079222        KENNETH C. K. MAINA
•    2018079294       JAGDEV   SINGH
•    2018077516     JOHN   MUTUGI   MUKABI
•    2018079239    STANLEY  KIMANZI  TITUS
•    2018079272    APOLLO  WASWA
•    2018079316   PETER  BAIYA  KIMANI
•    2018079330   JACKSON   KIPKIRUI
•    2018079295    SILPAH   ANYANGO  OWICH
•    2018079317   MARCUS  KIBET  TANUI
•    2018079193   JOHN  MAINA  KIRAGU
•    2018079297   MOSES  KAMAU  NDUATI
•    2018079282  MARY  WAIRIMU  MURIUKI
•    2018079283  SAMUEL  NDUNGU  GATURU
;



SELECT  *
FROM XXJICUG_AP_INVOICES_STG@JICOFPROD.COM 
WHERE OPERATING_UNIT = 'JHL_UG_LIF_OU';

SELECT * 
FROM JHL_OFA_PYMT_TRANSACTIONS
WHERE /*V_VOU_NO= '2018079222'
AND */V_VOU_NO NOT IN 
(
SELECT PAYMENT_VOUCHER
FROM APPS.XXJIC_AP_CLAIM_MAP@JICOFPROD.COM
WHERE/* PAYMENT_VOUCHER like  '%2018079222%' 
and  */LOB_NAME =  'JHL_UG_LIF_OU'
AND PAYMENT_VOUCHER  = V_VOU_NO

UNION ALL

SELECT  VOUCHER_NUM
FROM XXJICUG_AP_INVOICES_STG@JICOFPROD.COM 
WHERE OPERATING_UNIT = 'JHL_UG_LIF_OU'

)
AND INVOICE_AMOUNT <> 0; 


DELETE 
FROM JHL_OFA_PYMT_TRANSACTIONS
WHERE /*V_VOU_NO= '2018089524'
AND*/ V_VOU_NO NOT IN 
(
SELECT PAYMENT_VOUCHER
FROM APPS.XXJIC_AP_CLAIM_MAP@JICOFPROD.COM
WHERE/* PAYMENT_VOUCHER like  '%2018079222%' 
and  */LOB_NAME =  'JHL_UG_LIF_OU'
AND PAYMENT_VOUCHER  = V_VOU_NO

UNION ALL

SELECT  VOUCHER_NUM
FROM XXJICUG_AP_INVOICES_STG@JICOFPROD.COM 
WHERE OPERATING_UNIT = 'JHL_UG_LIF_OU'
AND VOUCHER_NUM = V_VOU_NO
)
AND INVOICE_AMOUNT <> 0; 


begin

DELETE 
FROM JHL_OFA_PYMT_VOUCHER_DTLS
WHERE /*V_VOU_NO= '2018079222'
AND */V_VOU_NO NOT IN 
(
SELECT PAYMENT_VOUCHER
FROM APPS.XXJIC_AP_CLAIM_MAP@JICOFPROD.COM
WHERE/* PAYMENT_VOUCHER like  '%2018079222%' 
and  */LOB_NAME =  'JHL_UG_LIF_OU'
AND PAYMENT_VOUCHER  = V_VOU_NO

UNION ALL

SELECT  VOUCHER_NUM
FROM XXJICUG_AP_INVOICES_STG@JICOFPROD.COM 
WHERE OPERATING_UNIT = 'JHL_UG_LIF_OU'
AND VOUCHER_NUM = V_VOU_NO
);
commit;
end;


