--select user from dual; -- JHLISFUADM
SELECT * FROM GNMT_CUSTOMER_MASTER WHERE N_CUST_REF_NO IN ('300986');

/*V_POLICY_NO, V_PYMT_FREQ , V_PLAN_CODE, N_SUM_COVERED,N_CONTRIBUTION, V_QUOTATION_ID,D_PROPOSAL_DATE, D_PROPOSAL_SUBMIT,D_COMMENCEMENT,D_NEXT_OUT_DATE,D_POLICY_END_DATE
N_PROPOSER_REF_NO,N_PREM_PAY_TERM,D_PREM_PAYING_END_DATE, V_CNTR_PREM_STAT_CODE,N_REQUEST_SA, V_PROPOSER_NAME, V_PAYER_NAME*/
SELECT  POLICY.*, PLAN.V_PLAN_NAME,POL_STATUS.V_STATUS_DESC AS POLICY_STATUS, PRM_STATUS.V_STATUS_DESC AS PREMIUM_STATUS, ADRS.V_ADD_ONE AS ADDRESS FROM GNMT_POLICY POLICY  
LEFT JOIN GNMM_PLAN_MASTER PLAN ON POLICY.V_PLAN_CODE = PLAN.V_PLAN_CODE 
LEFT JOIN GNMM_POLICY_STATUS_MASTER POL_STATUS ON POLICY.V_CNTR_STAT_CODE = POL_STATUS.V_STATUS_CODE
LEFT JOIN GNMM_POLICY_STATUS_MASTER PRM_STATUS ON POLICY.V_CNTR_PREM_STAT_CODE = PRM_STATUS.V_STATUS_CODE
LEFT JOIN GNDT_CUSTOMER_ADDRESS ADRS ON ADRS.N_CUST_REF_NO = POLICY.N_PROPOSER_REF_NO
WHERE V_POLICY_NO IN ('UI201900435763') ;

--- get a plan name---
select * from GNMM_PLAN_MASTER;

--get policy status and premium status
--  V_CNTR_PREM_STAT_CODE, V_CNTR_STAT_CODE --FROM GNMT_POLICY;
select * from GNMM_POLICY_STATUS_MASTER WHERE V_STATUS_DESC LIKE '%APL%';
SELECT  *  FROM GNMT_POLICY WHERE V_CNTR_STAT_CODE IN ('NB025','NB008');--SHOW    Accrued Interest

/*N_RECORD_SEQUENCE,V_RECEIPT_NO,V_CURRENCY_CODE,V_RECEIPT_STATUS*,D_STATUS,V_RECEIPT_CODE, N_DUE_AMT,N_RECEIPT_AMT,D_RECEIPT_DATE*/
SELECT * FROM REMT_RECEIPT WHERE V_POLICY_NO IN ('UI201900495790') AND V_RECEIPT_TABLE IN ('DETAIL') ORDER BY N_RECORD_SEQUENCE;

--receipt narration
select * from REMM_RECEIPT_CODE where v_receipt_code='RCT003';
---

SELECT N_RECORD_SEQUENCE,V_RECEIPT_NO,V_CURRENCY_CODE,D_STATUS,RECEIPT.V_RECEIPT_CODE,RECEIPT_CODE.V_RECEIPT_DESC,
           N_DUE_AMT,N_RECEIPT_AMT,D_RECEIPT_DATE 
           ,CASE V_RECEIPT_STATUS WHEN  'RE001'  THEN 'Processed' WHEN 'RE002' THEN 'Cancelled' ELSE V_RECEIPT_STATUS END AS V_RECEIPT_STATUS
           FROM REMT_RECEIPT RECEIPT LEFT JOIN REMM_RECEIPT_CODE RECEIPT_CODE ON RECEIPT.V_RECEIPT_CODE = RECEIPT_CODE.V_RECEIPT_CODE
           WHERE V_POLICY_NO IN ('UI201900495790') AND V_RECEIPT_TABLE IN ('DETAIL') ORDER BY N_RECORD_SEQUENCE;


--- RECEIPT STATUS DESCRIPTION---


SELECT * FROM PPMT_OUTSTANDING_PREMIUM ;

--RE001  - Processed
--RE002  - Cancelled

---outstanding premium -- SUM OF N_AMMOUNT
SELECT N_AMOUNT AS OUTSTANDING_PREM FROM PPMT_OUTSTANDING_PREMIUM WHERE V_POLICY_NO IN  ('UI201900495790') AND  V_STATUS LIKE ('A') FETCH NEXT 1 ROWS ONLY;

-----------------------------------------------------------
SELECT * from dba_objects WHERE
object_name like '%ACCRUED%' ORDER BY OBJECT_NAME;
SELECT owner, table_name, column_name FROM all_tab_columns WHERE column_name LIKE '%ACCRUED%';
DESC AMMT_ADBS_WITHDRAW_MASTER;




SELECT * FROM JHL_SALESFORCE_DATA;


DESC REMT_RECEIPT;
DESC GNMT_POLICY;
 

select * from GNMT_CUSTOMER_MASTER where N_CUST_REF_NO like (348569) ;


select * from GNDT_CUSTOMER_ADDRESS ;