--redate report requested by AUdit 

select A.V_POLICY_NO,A.D_REVIVE,A.V_REV_STATUS from PSMT_POLICY_REVIVAL A WHERE V_REVIVAL_TYPE IN ('RV','RD');

SELECT B.V_POLICY_NO,B.D_POLICY_END_DATE,B.D_COMMENCEMENT, A.D_REVIVE,A.V_REV_STATUS, B.V_CNTR_STAT_CODE FROM GNMT_POLICY B, PSMT_POLICY_REVIVAL A
WHERE V_CNTR_STAT_CODE IN ('NB024','NB051')
AND A.V_POLICY_NO=B.V_POLICY_NO
AND B.V_POLICY_NO IN (SELECT V_POLICY_NO FROM PSMT_POLICY_REVIVAL WHERE V_REVIVAL_TYPE IN ('RV','RD')) ;

SELECT * FROM PYMT_VOU_MASTER_PAYMENTS;

SELECT * FROM GNMM_POLICY_STATUS_MASTER;
SELECT * FROM PYDT_VOUCHER_PAYMENTS;
select * from JHL_OFA_PYMT_TRANSACTIONS;





select * from GNMT_DUAL_APPROVAL_REQUEST where V_POLICY_NO in ('UI201500120080','UI201500124324', 'UI201600173633', 'UI202100678253')
select * from GNMT_DUAL_APPROVAL_REQUEST where V_POLICY_NO = 'UI202100678253';

select * from GNMT_DUAL_APPROVAL_REQUEST WHERE V_PROCESS_TYPE IN ('CLAIM-GMAT','PR0015') order by D_REQUESTED desc ;

SELECT * FROM PSMT_POLICY_REVIVAL WHERE V_POLICY_NO IN ('UI201800344384');



V_PROCESS_TYPE.GNMT_DUAL_APPROVAL_REQUEST= V_PROCESS_ID.GNMM_PROCESS_MASTER

 V_PROCESS_NAME FROM GNMM_PROCESS_MASTER

AND TO_DATE(D_REQUESTED,'DD/MM/RRRR')   BETWEEN TO_DATE('01-MAY-20','DD/MM/RRRR')  AND TO_DATE('31-MAR-21','DD/MM/RRRR') 

order by D_REQUESTED desc;

select * from GNMM_PROCESS_MASTER where V_PROCESS_ID IN ('PR0015', 'CLAIM-GMAT');

select * from GNMM_PROCESS_MASTER where V_PROCESS_NAME LIKE '%REVIVAL%'

RV002    REVIVAL PROCESS
PR0022    REVIVAL - REDATING
RV001    A/C REVIVAL FROM LOAN
PR0015_RD    RIDER REVIVAL
PR0015    REVIVAL - LAPSE;

SELECT V_POLICY_NO,D_REVIVE,V_REVIVAL_TYPE 
FROM PSMT_POLICY_REVIVAL 
WHERE TO_DATE(D_REVIVE,'DD/MM/RRRR')   BETWEEN TO_DATE('01-JAN-09','DD/MM/RRRR')  AND TO_DATE(sysdate,'DD/MM/RRRR')
ORDER BY D_REVIVE DESC;