SELECT B.V_AGENT_CODE,A.* FROM AMMT_POL_COMM_DETAIL  A,AMMM_AGENT_MASTER B WHERE V_COMM_STATUS  IN 'UP' 
AND A.N_SUB_AGENT_NO=B.N_AGENT_NO;

SELECT * FROM AMMT_POL_COMM_DETAIL WHERE V_POLICY_NO IN 'CL0289' ;

SELECT * FROM AMMM_AGENT_MASTER;

SELECT  B.V_PLAN_CODE,A.V_POLICY_NO, A.V_PLAN_CODE FROM GNMT_POLCOMP_RIDERS A, GNMT_POLICY B 
/*where A.V_POLICY_NO IN 'UG201900513146'*/
WHERE B.V_POLICY_NO=A.V_POLICY_NO
ORDER BY A.V_PLAN_CODE DESC;

SELECT * FROM GNMT_POLCOMP_RIDERS;

SELECT * FROM GNMT_POLICY WHERE V_POLICY_NO IN 'UG201900513146' order by A.V_PLAN_CODE_1 desc;

--ALL RIDERS WITH RISK CATEGORIES 

SELECT * FROM GNMM_PLAN_EVENT_LINK;
SELECT * FROM GNMM_PLAN_MASTER;
select * from RILU_RISK_CATEGORY_MASTER;
SELECT A.V_PLAN_CODE,B.V_PLAN_NAME,A.V_REINS_RISK_CATEGORY, C.V_RISK_CATEGORY_DESC FROM GNMM_PLAN_EVENT_LINK A, GNMM_PLAN_MASTER B, RILU_RISK_CATEGORY_MASTER C
WHERE A.V_PLAN_CODE=B.V_PLAN_CODE
AND A.V_REINS_RISK_CATEGORY=C.V_RISK_CATEGORY
;