SELECT a.V_ROLE_NAME, V_ROLE_DESC, a.V_PROG_ID, V_PROG_DESC, V_USER_NAME, a.V_MENU_NAME, c.D_APPROVED as ROLE_APPROVED_DATE, E.ACCOUNT_STATUS, E.EXPIRY_DATE,E.LOCK_DATE
FROM GNDT_ROLE_PROG a, GNLU_PROG_MASTER b, GNDT_UM_USER_PRIVS_TASK c, JHL_ROLE d, dba_users E
WHERE a.V_PROG_ID = b.V_PROG_ID
AND V_TYPE='F'
AND a.V_ROLE_NAME = V_GRANTROLE_NAME
AND a.V_ROLE_NAME = d.V_ROLE_NAME
AND E.USERNAME=V_USER_NAME
--AND a.V_ROLE_NAME IN  ('R200','R201','R202','R203','R204','R205','R206','R207','R208','R209','R211')
AND a.V_ROLE_NAME NOT IN ('R210') 
AND a.V_MENU_NAME = b.V_MENU_NAME
AND NVL(b.V_STATUS,'X') = 'A'
and v_user_name IN (SELECT V_USER_ID FROM GNMT_USER WHERE V_STAT = 'A');

select * from dba_users;

ACCOUNT_STATUS

EXPIRY_DATE
LOCK_DATE
USERNAME;

select * from GNDT_UM_USER_PRIVS_TASK;